### ISSUE TITLE
Questions about mutable globals in `aot.CompiledModule`

### ISSUE THREAD

**Issue by ScottTodd** [nod-ai/SHARK-Turbine#101]
I have a Colab notebook that I'd like to port from using TensorFlow to using PyTorch + SHARK-Turbine: https://colab.research.google.com/github/openxla/iree/blob/main/samples/variables_and_state/variables_and_state.ipynb. I'm mostly referencing code in [`tests/aot/globals_test.py`](https://github.com/nod-ai/SHARK-Turbine/blob/main/tests/aot/globals_test.py) and [`tests/aot/jittable_test.py`](https://github.com/nod-ai/SHARK-Turbine/blob/main/tests/aot/jittable_test.py).

The TF Python module looks like this:
```python
class CounterModule(tf.Module):
  def __init__(self):
    super().__init__()
    self.counter = tf.Variable(0)

  @tf.function(input_signature=[])
  def get_value(self):
    return self.counter

  @tf.function(input_signature=[tf.TensorSpec([], tf.int32)])
  def set_value(self, new_value):
    self.counter.assign(new_value)

  @tf.function(input_signature=[tf.TensorSpec([], tf.int32)])
  def add_to_value(self, x):
    self.counter.assign(self.counter + x)

  @tf.function(input_signature=[])
  def reset_value(self):
    self.counter.assign(0)
```

Yes, this doesn't look like a typical neural network program, but I find it easier to explore the programming API with as few extra "layers" (ha!) involved.

Most of the methods were straightforward to port:
```python
from iree.compiler.ir import Context
import shark_turbine.aot as aot
import torch

counter_tensor = torch.tensor(0, dtype=torch.int32)
value_example = torch.tensor(1, dtype=torch.int32)
zero_tensor = torch.tensor(0, dtype=torch.int32)

class CounterModule(aot.CompiledModule):
  counter = aot.export_global(counter_tensor, mutable=True)
  zero = aot.export_global(zero_tensor)

  def get_value(self):
    return self.counter

  def set_value(self, value=aot.abstractify(value_example)):
    self.counter = value

  def reset_value(self):
    self.counter = self.zero

counter_instance = CounterModule(context=Context())
print(aot.CompiledModule.get_mlir_module(counter_instance))
```

I'm having trouble porting the "add_to_value" function that reads and writes to the global variable in the same function though. Here's what I've tried so far:

```python
  # TypeError: unsupported operand type(s) for +: 'IrGlobalTensor' and 'IrImmediateTensor'
  def add_to_value(self, value=aot.abstractify(value_example)):
    self.counter = self.counter + value
    
  # TypeError: unsupported operand type(s) for +=: 'IrGlobalTensor' and 'IrImmediateTensor'
  def add_to_value(self, value=aot.abstractify(value_example)):
    self.counter += value

  # RuntimeError: Calls to exported functions not yet supported
  def add_to_value(self, value=aot.abstractify(value_example)):
    self.counter = self.get_value() + value
```

Am I missing something, or is this usage not supported yet? I also see the  `aot.IREE.tensor_update` function, but I'm not sure yet how to use that.

**Comment by stellaraccident** [comment]
Multiple API loose threads here that we punted on... thanks for the issue. Will require some revs to address. I think the first two are what should be made to work and are just limitations we need to relax...

**Comment by ScottTodd** [comment]
I'm trying to debug some suspected issues with in-place operations (specifically `index_put_`) and I still see `TypeError: unsupported operand type(s) for +=: 'IrGlobalTensor' and 'IrImmediateTensor'` for the usage of `+=` above. (I figured `add_` or `+=` would be good to validate before jumping to `index_put_`)

**Comment by vivekkhandelwal1** [comment]
Hi @ScottTodd, do we need to keep this issue?

**Comment by ScottTodd** [comment]
We should move this issue to https://github.com/iree-org/iree-turbine
