### ISSUE TITLE
Generate and publish Python API docs

### ISSUE THREAD

**Issue by ScottTodd** [nod-ai/SHARK-Turbine#106]
Could be too early in the project right now, but I think users would find it helpful to view API documentation pages instead of just needing to read through source files, samples, and tests. I would also like to link to API docs from https://iree.dev/guides/ml-frameworks/pytorch/.

IREE Python used readthedocs (with mixed results): https://iree-python-api.readthedocs.io/en/latest/
* I also evaluated [mkdocstrings](https://mkdocstrings.github.io/) for integrated into IREE's mkdocs website, but it was awkward: https://github.com/openxla/iree/issues/5477#issuecomment-1612221943

Could see what PyTorch uses for https://pytorch.org/docs/stable/index.html (sample page: [`torch.nn.Linear`](https://pytorch.org/docs/stable/generated/torch.nn.Linear.html))

Even if we don't end up publishing API docs, going through and adding docstrings and help text could still be useful.

**Comment by vivekkhandelwal1** [comment]
Hi @ScottTodd, any update on this issue?
