### ISSUE TITLE
Command line "--mlir-print-ir-after-all" not supported on shark-turbine

### ISSUE THREAD

**Issue by SuperCarrot2012** [nod-ai/SHARK-Turbine#118]
In this file : SHARK-Turbine/python/shark_turbine/dynamo/backends/cpu.py
When i set_flags like that:
session.set_flags("--mlir-print-ir-after-all")
There will be an error that option is not supported.

So how can i enable this option?

**Comment by ScottTodd** [comment]
Session flags are passed down to the [`ireeCompilerSessionSetFlags`](https://github.com/openxla/iree/blob/7b92a6d38599d3255b4513f1019c540a3401cfd3/compiler/bindings/c/iree/compiler/embedding_api.h#L150-L154) C API function:
```c
// Sets session-local flags. These are a subset of flags supported by CLI
// tools and are privately scoped.
IREE_EMBED_EXPORTED iree_compiler_error_t *
ireeCompilerSessionSetFlags(iree_compiler_session_t *session, int argc,
                            const char *const *argv);
```
The code backing that is in [`API/Internal/CompilerDriver.cpp`](https://github.com/openxla/iree/blob/7b92a6d38599d3255b4513f1019c540a3401cfd3/compiler/src/iree/compiler/API/Internal/CompilerDriver.cpp#L258-L378), and it looks like only some IREE-specific options are configurable there. Generic MLIR options may need to go through [`ireeCompilerSetupGlobalCL`](https://github.com/openxla/iree/blob/7b92a6d38599d3255b4513f1019c540a3401cfd3/compiler/bindings/c/iree/compiler/embedding_api.h#L102-L114) (not exposed to Python?).

I'm not sure if there is a way to use that flag within Dynamo (JIT workflows), but you could use AOT workflows and either the [IREE Python "tools" APIs](https://iree-python-api.readthedocs.io/en/latest/compiler/tools.html) (see `extra_args` on `CompilerOptions`), or the native CLI tools which that Python API wraps (`iree-compile`).

Here's a Colab notebook showing how to use the CLI tools with `--mlir-print-ir-after-all`: https://colab.research.google.com/gist/ScottTodd/9abaf1f5bf2e38f35c5676f674b0e541/turbine-mlir-print-ir-after-all.ipynb

**Comment by stellaraccident** [comment]
This flag only applies to mlir command line tools. We've been meaning to add various debug ability options to Turbine to provide similar capabilities.

There is a back door that will partially work today but it is global. See the user of _initializeGlobalCL in this branch: https://github.com/nod-ai/SHARK-Turbine/commit/1d6b080bd8d59784ab918c4275ce0f0d4b391112

Iirc, there is more that needs to be done to get IR printing working from the API. I think you also need to disable threading explicitly.

I can use this as a driver to enhance turbine debugging generally. To date we mostly get the unit IR and use CL tools when debugging. That will always be the most tried and true but we can make the integrated experience better too.

**Comment by SuperCarrot2012** [comment]
> This flag only applies to mlir command line tools. We've been meaning to add various debug ability options to Turbine to provide similar capabilities.
> 
> There is a back door that will partially work today but it is global. See the user of _initializeGlobalCL in this branch: [1d6b080](https://github.com/nod-ai/SHARK-Turbine/commit/1d6b080bd8d59784ab918c4275ce0f0d4b391112)
> 
> Iirc, there is more that needs to be done to get IR printing working from the API. I think you also need to disable threading explicitly.
> 
> I can use this as a driver to enhance turbine debugging generally. To date we mostly get the unit IR and use CL tools when debugging. That will always be the most tried and true but we can make the integrated experience better too.

Problem solved, thanks very much!
