### ISSUE TITLE
Generalize stateless_llama.py

### ISSUE THREAD

**Issue by IanNod** [nod-ai/SHARK-Turbine#186]
We need to look to extend and generalize what is currently stateless_llama.py to work with essentially any hugging face llm model.

**Comment by vivekkhandelwal1** [comment]
Hi @IanNod, do we still need this issue?

**Comment by IanNod** [comment]
Closing for now as stateless llama is fairly deprecated in it's current form

**Comment by bhbruce** [comment]
Hi @IanNod 
What's the suggested path for running e2e LLama model?
