### ISSUE TITLE
Lowering `onnx.transpose`  to torch

### ISSUE THREAD

**Issue by rsuderman** [nod-ai/SHARK-Turbine#238]

**Comment by wu-s-john** [comment]
I can work on this if this is available

**Comment by rsuderman** [comment]
> I can work on this if this is available

I have an implementation located here:
https://github.com/rsuderman/torch-mlir/tree/Transpose

I was mostly waiting on the review of https://github.com/llvm/torch-mlir/pull/2634 before setting up the next PR. Happy to send the review your way.

**Comment by wu-s-john** [comment]
ooo okay, I can take a look
