### ISSUE TITLE
ONNX Conv Op

### ISSUE THREAD

**Issue by AmosLewis** [nod-ai/SHARK-Turbine#253]

**Comment by AmosLewis** [comment]
densenetblur121d_test_vaiq.default.onnx.torch.mlir:461:12: error: internal error: jit global source initialization order invalid: global "__hoisted_i32" has no value
    %457 = torch.operator "onnx.Conv"(%455, %456) {torch.onnx.dilations = [1 : si64, 1 : si64], torch.onnx.group = 64 : si64, torch.onnx.kernel_shape = [3 : si64, 3 : si64], torch.onnx.pads = [0 : si64, 0 : si64, 0 : si64, 0 : si64], torch.onnx.strides = [2 : si64, 2 : si64]} : (!torch.vtensor<[?,?,?,?],f32>, !torch.vtensor<[64,1,3,3],f32>) -> !torch.vtensor<[?,64,?,?],f32> 
           ^

**Comment by AmosLewis** [comment]
```
eca_nfnet_l0.ra2_in1k_train_vaiq.default.torch-onnx.mlir:1192:13: error: failed to legalize operation 'torch.aten.convolution' that was explicitly marked illegal
    %1188 = torch.operator "onnx.Conv"(%1187, %1043) {torch.onnx.dilations = [1 : si64], torch.onnx.group = 1 : si64, torch.onnx.kernel_shape = [5 : si64], torch.onnx.pads = [2 : si64, 2 : si64], torch.onnx.strides = [1 : si64]} : (!torch.vtensor<[1,1,256],f32>, !torch.vtensor<[1,1,5],f32>) -> !torch.vtensor<[1,1,256],f32> 
            ^
eca_nfnet_l0.ra2_in1k_train_vaiq.default.torch-onnx.mlir:1192:13: note: see current operation: %2844 = "torch.aten.convolution"(%2841, %2843, %265, %2839, %2838, %2839, %43, %863, %48) : (!torch.vtensor<[1,1,256],!torch.qint8>, !torch.vtensor<[1,1,5],!torch.qint8>, !torch.none, !torch.list<int>, !torch.list<int>, !torch.list<int>, !torch.bool, !torch.list<int>, !torch.int) -> !torch.vtensor<[1,1,256],si32>

```

**Comment by zjgarvey** [comment]
@AmosLewis : There isn't a linalg named op for quantized 1-d convolution yet.
1. we could add another named op
2. we could unsqueeze the last dim for the input and weight and pass to a 2d qconv
3. we could prevent fusion for 1d convolution ops and just do it as an f32 conv. 

What would you like to do?

**Comment by AmosLewis** [comment]
New conv error
```
ecaresnet26t_vaiq.default.onnx.torch.mlir:319:12: error: failed to legalize operation 'torch.aten.convolution' that was explicitly marked illegal
    %287 = torch.aten.convolution %284, %81, %none, %286, %285, %286, %false, %224, %int1 : !torch.vtensor<[1,1,256],f32>, !torch.vtensor<[1,1,5],f32>, !torch.none, !torch.list<int>, !torch.list<int>, !torch.list<int>, !torch.bool, !torch.list<int>, !torch.int -> !torch.vtensor<[1,1,256],f32>
           ^
ecaresnet26t_vaiq.default.onnx.torch.mlir:319:12: note: see current operation: %1726 = "torch.aten.convolution"(%1723, %1725, %160, %1721, %1720, %1721, %38, %468, %43) : (!torch.vtensor<[1,1,256],!torch.qint8>, !torch.vtensor<[1,1,5],!torch.qint8>, !torch.none, !torch.list<int>, !torch.list<int>, !torch.list<int>, !torch.bool, !torch.list<int>, !torch.int) -> !torch.vtensor<[1,1,256],si32>
```

**Comment by AmosLewis** [comment]
> The third option is very straightforward. E.g., we could add
> 
> ```c++
>     int64_t inputRank = cast<ValueTensorType>(operands[0].getType()).getSizes().size();
>     if (isa<Torch::AtenConvolutionOp>(op) && inputRank < 4) 
>       return rewriter.notifyMatchFailure(op, "1-d quantized convolution is not supported");
> ```
> 
> near the beginning of https://github.com/llvm/torch-mlir/blob/78d0fa8998c93514737f7075f4f2a3f4a9ff7b57/lib/Dialect/Torch/Transforms/FuseQuantizedOps.cpp#L55.

This options is greate. I test with all the models conv failed. It works fine. https://github.com/llvm/torch-mlir/pull/3601
