### ISSUE TITLE
Slice

### ISSUE THREAD

**Issue by wu-s-john** [nod-ai/SHARK-Turbine#259]
This is the Onnx lowering for Slice to Torch-MLIR

**Comment by wu-s-john** [comment]
Our standard approach to model conversion has been streamlined due to the typically straightforward one-to-one mapping between ONNX and PyTorch operations. The ONNX Slice operation, however, presents an interesting deviation, primarily in how it handles multiple axes and steps.

# Key Points:

## Axes and Steps in ONNX Slice:

The ONNX `Slice` operation allows for slicing along multiple axes with specified steps, whereas PyTorch's `aten.slice` operates along a single axis at a time without native step functionality.
Static Nature of Axes and Steps:

Critically, in ONNX, `axes` and `steps` are attribute inputs, typically known ahead of time. This static nature makes our proposed conversion strategy feasible and reliable.

## Proposed Method and Example:
To effectively translate the multi-axis, step-inclusive ONNX Slice to a series of PyTorch aten.slice operations, we can leverage the pre-known axes and steps.

For instance, an ONNX Slice: Slice(data, starts=[1, 0], ends=[3, -1], axes=[0, 1], steps=[1, 2]) on a 2D tensor would translate to the following in PyTorch:

```python

# Assuming 'tensor' is the input tensor
sliced_tensor = tensor
sliced_tensor = aten.slice(sliced_tensor, 0, 1, 3, 1)  # Slice along axis 0
sliced_tensor = aten.slice(sliced_tensor, 1, 0, tensor.size(1) - 1, 2)  # Slice along axis 1 with step
```

Invitation for Feedback:
Given the static nature of the axes and steps in ONNX, this conversion method appears both feasible and robust. I would love to hear feedback and insights on this approach, particularly regarding any potential edge cases or optimization opportunities.

Thank you for considering this strategy, and I eagerly await your thoughts and suggestions.

**Comment by wu-s-john** [comment]
Links:

1. https://onnx.ai/onnx/operators/onnx__Slice.html#l-onnx-doc-slice
2. https://pytorch.org/cppdocs/api/function_namespaceat_1ae6bdafd2514da71bc5a656a649bcb575.html#_CPPv4N2at5sliceERKN2at6TensorE7int64_tN3c108optionalI7int64_tEEN3c108optionalI7int64_tEE7int64_t

**Comment by wu-s-john** [comment]
Would love to get some feedback @stellaraccident  @vivekkhandelwal1 @rsuderman

**Comment by rsuderman** [comment]
I was actually in progress of implementing, so I am happy to shelve my version and let you take over.

100% this is how you want to implement it. There are some fiddly things with the types, namely how to extract the values from the bounds tensors. Some operands are optional, this means  you do not know what operand matches to which semantic behavior until you know the total number of operands.

The other issue is determining intermediate types. See a case such as below:

```
  func.func @test_slice(%arg0: !torch.vtensor<[20,10,5],f32>, %arg1: !torch.vtensor<[2],si64>, %arg2: !torch.vtensor<[2],si64>, %arg3: !torch.vtensor<[2],si64>, %arg4: !torch.vtensor<[2],si64>) -> !torch.vtensor<[3,10,5],f32> attributes {torch.onnx_meta.ir_version = 7 : si64, torch.onnx_meta.opset_version = 13 : si64, torch.onnx_meta.producer_name = "backend-test", torch.onnx_meta.producer_version = ""} {
    %0 = torch.operator "onnx.Slice"(%arg0, %arg1, %arg2, %arg3, %arg4) : (!torch.vtensor<[20,10,5],f32>, !torch.vtensor<[2],si64>, !torch.vtensor<[2],si64>, !torch.vtensor<[2],si64>, !torch.vtensor<[2],si64>) -> !torch.vtensor<[3,10,5],f32>
    return %0 : !torch.vtensor<[3,10,5],f32>
  }
```

We know that the slice includes taking the first axis, however when decomposing into multiple slices it is unknown whether the first or second slice targets the first axis. Any matching dimensions we can always say stays the same, however it is unknown whether the changing axis actually changes.

**Comment by rsuderman** [comment]
Some handy test files
[slice.zip](https://github.com/nod-ai/SHARK-Turbine/files/13688617/slice.zip)

**Comment by wu-s-john** [comment]
> The other issue is determining intermediate types. See a case such as below:

When you say intermediate types, do you mean dividing the the values of a dimension of a slice to a different value?

> We know that the slice includes taking the first axis, however when decomposing into multiple slices it is unknown whether the first or second slice targets the first axis. Any matching dimensions we can always say stays the same, however it is unknown whether the changing axis actually changes.

I think the axis where you slice the axis depends on the variable `axes`. `axes[i]` will indicate that you slice **only** on `i`th dimension. Then, `start[i]` will be the initial position you slice on the `ith` dimension, then `end[i]` will be the end position of the slice on `ith` dimension. `step[i]` will be the stride of the slice.

**Comment by wu-s-john** [comment]
Yah, I can take over the feature and send the changes by the end of the weekend!

**Comment by rsuderman** [comment]
> Yah, I can take over the feature and send the changes by the end of the weekend!

Awesome! Just tag me when its ready and I will review.

**Comment by wu-s-john** [comment]
@rsuderman 

I realize that for examples like this:

```
 func.func @test_slice(%arg0: !torch.vtensor<[20,10,5],f32>, %arg1: !torch.vtensor<[2],si64>, %arg2: !torch.vtensor<[2],si64>, %arg3: !torch.vtensor<[2],si64>, %arg4: !torch.vtensor<[2],si64>) -> !torch.vtensor<[3,10,5],f32> attributes {torch.onnx_meta.ir_version = 7 : si64, torch.onnx_meta.opset_version = 13 : si64, torch.onnx_meta.producer_name = "backend-test", torch.onnx_meta.producer_version = ""} {
    %0 = torch.operator "onnx.Slice"(%arg0, %arg1, %arg2, %arg3, %arg4) : (!torch.vtensor<[20,10,5],f32>, !torch.vtensor<[2],si64>, !torch.vtensor<[2],si64>, !torch.vtensor<[2],si64>, !torch.vtensor<[2],si64>) -> !torch.vtensor<[3,10,5],f32>
    return %0 : !torch.vtensor<[3,10,5],f32>
  }
```

We don't know the actual contents of the args `arg1`, `arg2` and `arg3`. That being said, the output `vtensor` would generate `?` dimensions.

We can only know the dimensions of the output tensors if the arguments are known ahead of time. I used the `onnx-importer` and  it generated the following code.

```
module {
  func.func @SliceModel(%arg0: !torch.vtensor<[1,3,4],f32>) -> !torch.vtensor<[1,2,2],f32> attributes {torch.onnx_meta.ir_version = 9 : si64, torch.onnx_meta.opset_version = 20 : si64, torch.onnx_meta.producer_name = "onnx-example", torch.onnx_meta.producer_version = ""} {
    %0 = torch.vtensor.literal(dense<[0, 1]> : tensor<2xsi64>) : !torch.vtensor<[2],si64>
    %1 = torch.vtensor.literal(dense<[2, 3]> : tensor<2xsi64>) : !torch.vtensor<[2],si64>
    %2 = torch.vtensor.literal(dense<[1, 2]> : tensor<2xsi64>) : !torch.vtensor<[2],si64>
    %3 = torch.vtensor.literal(dense<1> : tensor<2xsi64>) : !torch.vtensor<[2],si64>
    %4 = torch.operator "onnx.Slice"(%arg0, %0, %1, %2, %3) : (!torch.vtensor<[1,3,4],f32>, !torch.vtensor<[2],si64>, !torch.vtensor<[2],si64>, !torch.vtensor<[2],si64>, !torch.vtensor<[2],si64>) -> !torch.vtensor<[1,2,2],f32>
    return %4 : !torch.vtensor<[1,2,2],f32>
  }
}
```

So, we can mostly deduce the size of the resulting tensor if they are declared as a `constant` or `literal`. I will write the code such that it determines intermediate shapes based on if the arguments are literal or constants.

**Comment by rsuderman** [comment]
You are correct with one minor appendum - we can also look at the result type to know the output shape. Sometimes models will show the value as being dynamically computed while guaranteeing the total size. Assuming the invariants hold true we can use whichever limitation is more accurate.

**Comment by wu-s-john** [comment]
Implemented and now in a PR!

https://github.com/llvm/torch-mlir/pull/2696
