### ISSUE TITLE
Mod

### ISSUE THREAD

**Issue by Groverkss** [nod-ai/SHARK-Turbine#267]

**Comment by Groverkss** [comment]
@pavs315 is taking this op

**Comment by vivekkhandelwal1** [comment]
@pavs315 are you still working on this op?

**Comment by pavs315** [comment]
@vivekkhandelwal1 hi yes, I'm currently working on the tests.

**Comment by vivekkhandelwal1** [comment]
Closed by https://github.com/llvm/torch-mlir/commit/c51e2130f269615e0418ca421e5976f94022daee
