### ISSUE TITLE
ConstantOfShape

### ISSUE THREAD

**Issue by PhaneeshB** [nod-ai/SHARK-Turbine#284]

**Comment by PhaneeshB** [comment]
It seems that [constantOfShape](https://onnx.ai/onnx/operators/onnx__ConstantOfShape.html#l-onnx-doc-constantofshape) has a corresponding map to [torch.full](https://pytorch.org/docs/stable/generated/torch.full.html#torch.full)
There is just one thing that `torch.full` is expecting a scalar `fill_value` and 
the type of the result is inferred from the type of the `fill_value`

My understanding is that, in order to get the right scalar for `fill_value` we need to get the `value` attr and cast it to the appropriate scalar attr type to be fed into `torch.full`
I see we have methods to get attrs whose type is already known but here we need to get the type info from the attr itself
I was thinking of an if else ladder / switch case to map each attr type to a the appropriate cast but would prefer a shorter, more succinct way. 
Need help to figure out the right way to go about it.

**Comment by PhaneeshB** [comment]
It seems that of all the ops on the ONNX ops page,
Constant and ConstantOfShape ops are ones which pass a 0-D tensor value as an `attribute` and need the attribute's dtype information to give out the result.
The task is to read the attribute as a tensor (which is default when read as and operand) and acc. to the dtype of the 0-D tensor set the resulting tensor's output.

Here's a [WIP patch](https://github.com/llvm/torch-mlir/pull/2747) that can read the attribute as integer / float constants and accordingly populate the `fill_value` attr.

I've used the following as test cases for constant attributes
```
func.func @test_constant_of_shape_float32(%arg0: !torch.vtensor<[3], si64>) -> !torch.vtensor<[2,3,4], f32> attributes {torch.onnx_meta.ir_version = 9 : si64, torch.onnx_meta.opset_version = 20 : si64, torch.onnx_meta.producer_name = "backend-test", torch.onnx_meta.producer_version = ""} {
  %0 = torch.operator "onnx.ConstantOfShape"(%arg0) {torch.onnx.value = 4.3 : f32}: (!torch.vtensor<[3], si64>) -> !torch.vtensor<[2,3,4],f32>
  return %0 : !torch.vtensor<[2,3,4],f32>
}
``` 
```
func.func @test_constant_of_shape_int64(%arg0: !torch.vtensor<[3], si64>) -> !torch.vtensor<[2,3,4], si64> attributes {torch.onnx_meta.ir_version = 9 : si64, torch.onnx_meta.opset_version = 20 : si64, torch.onnx_meta.producer_name = "backend-test", torch.onnx_meta.producer_version = ""} {
  %0 = torch.operator "onnx.ConstantOfShape"(%arg0) {torch.onnx.value = 4 : si64}: (!torch.vtensor<[3], si64>) -> !torch.vtensor<[2,3,4], si64>
  return %0 : !torch.vtensor<[2,3,4], si64>
}
```

I've made attempts to pass vtensor as attributes as follows which results in `error: expected attribute value`
```
func.func @test_constant_of_shape_float32_tensor1(%arg0: !torch.vtensor<[3], si64>) -> !torch.vtensor<[2,3,4], f32> attributes {torch.onnx_meta.ir_version = 9 : si64, torch.onnx_meta.opset_version = 20 : si64, torch.onnx_meta.producer_name = "backend-test", torch.onnx_meta.producer_version = ""} {
  %none = torch.constant.none
  %0 = torch.prim.ListConstruct : () -> !torch.list<int>
  %1 = torch.aten.zeros %0, %none, %none, %none, %none : !torch.list<int>, !torch.none, !torch.none, !torch.none, !torch.none -> !torch.vtensor<[],f32>
  %2 = torch.operator "onnx.ConstantOfShape"(%arg0) {torch.onnx.value = %1 : !torch.vtensor<[],f32>}: (!torch.vtensor<[3], si64>) -> !torch.vtensor<[2,3,4],f32>
  return %2 : !torch.vtensor<[2,3,4],f32>
}
```
```
func.func @test_constant_of_shape_float32_tensor2(%arg0: !torch.vtensor<[3], si64>) -> !torch.vtensor<[2,3,4], f32> attributes {torch.onnx_meta.ir_version = 9 : si64, torch.onnx_meta.opset_version = 20 : si64, torch.onnx_meta.producer_name = "backend-test", torch.onnx_meta.producer_version = ""} {
  %0 = torch.operator "onnx.ConstantOfShape"(%arg0) {torch.onnx.value = torch.vtensor.literal(dense<1.00e+00> : tensor<f32>) : !torch.vtensor<[],f32>}: (!torch.vtensor<[3], si64>) -> !torch.vtensor<[2,3,4],f32>
  return %0 : !torch.vtensor<[2,3,4],f32>
}
```

**Comment by rsuderman** [comment]
Glancing through your implementation it is looking good to me. Obviously you still need to get the splat value out of the dense elements attr but that should be pretty striaghtforward.

**Comment by PhaneeshB** [comment]
Another way would be to directly output a `torch.vtensor.literal` as is done for `ConstantOp`
was trying to figure out a way to convert the operand shape (Value) to a SmallVector<int64_t> 
Still need to figure out a way to directly convert it. lmk if there are examples that I can refer for it
updating the WIP PR mean while to unblock

**Comment by PhaneeshB** [comment]
Updated the PR : https://github.com/llvm/torch-mlir/pull/2747
@rsuderman @kumardeepakamd

**Comment by PhaneeshB** [comment]
Merged
