### ISSUE TITLE
BatchNormalization

### ISSUE THREAD

**Issue by vivekkhandelwal1** [nod-ai/SHARK-Turbine#285]

**Comment by AmosLewis** [comment]
```
eca_nfnet_l0.ra2_in1k_train_vaiq.default.onnx.torch.mlir:309:14: error: failed to legalize operation 'torch.operator' that was explicitly marked illegal
    %305:3 = torch.operator "onnx.BatchNormalization"(%71, %72, %299, %300, %304) {torch.onnx.epsilon = 9.99999974E-6 : f32, torch.onnx.momentum = 1.000000e+00 : f32, torch.onnx.training_mode = 1 : si64} : (!torch.vtensor<[1,16,27],f32>, !torch.vtensor<[16],f32>, !torch.vtensor<[16],f32>, !torch.vtensor<[16],f32>, !torch.vtensor<[16],f32>) -> (!torch.vtensor<[1,16,27],f32>, !torch.vtensor<[16],f32>, !torch.vtensor<[16],f32>) 
             ^
eca_nfnet_l0.ra2_in1k_train_vaiq.default.onnx.torch.mlir:309:14: note: see current operation: %665:3 = "torch.operator"(%143, %145, %638, %645, %664) <{name = "onnx.BatchNormalization"}> {torch.onnx.epsilon = 9.99999974E-6 : f32, torch.onnx.momentum = 1.000000e+00 : f32, torch.onnx.training_mode = 1 : si64} : (!torch.vtensor<[1,16,27],f32>, !torch.vtensor<[16],f32>, !torch.vtensor<[16],f32>, !torch.vtensor<[16],f32>, !torch.vtensor<[16],f32>) -> (!torch.vtensor<[1,16,27],f32>, !torch.vtensor<[16],f32>, !torch.vtensor<[16],f32>)

```
@vivekkhandelwal1 Need revisit

**Comment by vivekkhandelwal1** [comment]
> python ./run.py --tolerance 0.001 0.001 --cachedir /proj/gdba/shark/cache -f onnx -g models --mode onnx --report -j 24 --tests onnx/models/eca_nfnet_l0.ra2_in1k_train_vaiq
> 
> ```
> eca_nfnet_l0.ra2_in1k_train_vaiq.default.onnx.torch.mlir:309:14: error: failed to legalize operation 'torch.operator' that was explicitly marked illegal
>     %305:3 = torch.operator "onnx.BatchNormalization"(%71, %72, %299, %300, %304) {torch.onnx.epsilon = 9.99999974E-6 : f32, torch.onnx.momentum = 1.000000e+00 : f32, torch.onnx.training_mode = 1 : si64} : (!torch.vtensor<[1,16,27],f32>, !torch.vtensor<[16],f32>, !torch.vtensor<[16],f32>, !torch.vtensor<[16],f32>, !torch.vtensor<[16],f32>) -> (!torch.vtensor<[1,16,27],f32>, !torch.vtensor<[16],f32>, !torch.vtensor<[16],f32>) 
>              ^
> eca_nfnet_l0.ra2_in1k_train_vaiq.default.onnx.torch.mlir:309:14: note: see current operation: %665:3 = "torch.operator"(%143, %145, %638, %645, %664) <{name = "onnx.BatchNormalization"}> {torch.onnx.epsilon = 9.99999974E-6 : f32, torch.onnx.momentum = 1.000000e+00 : f32, torch.onnx.training_mode = 1 : si64} : (!torch.vtensor<[1,16,27],f32>, !torch.vtensor<[16],f32>, !torch.vtensor<[16],f32>, !torch.vtensor<[16],f32>, !torch.vtensor<[16],f32>) -> (!torch.vtensor<[1,16,27],f32>, !torch.vtensor<[16],f32>, !torch.vtensor<[16],f32>)
> ```
> 
> @vivekkhandelwal1 Need revisit

@AmosLewis The support for this case is added by https://github.com/llvm/torch-mlir/pull/3597

**Comment by vivekkhandelwal1** [comment]
Fixed by https://github.com/llvm/torch-mlir/pull/3597

CC: @AmosLewis
