### ISSUE TITLE
torch.aten.reflection_pad1d

### ISSUE THREAD

**Issue by kumardeepakamd** [nod-ai/SHARK-Turbine#293]
Support torch.aten.reflection_pad1d in torch MLIR

**Comment by frederik-h** [comment]
I am working on the torch.aten.reflection_pad2d operator and it is essentially done, but I won't be able to finish the PR before Christmas. I am not sure if it is worth to do a separate implementation of the 1d operator, i.e. it should be possible to reuse and simplify the 2d implementation.

**Comment by stellaraccident** [comment]
@kumardeepakamd / @frederik-h can you coordinate?

**Comment by frederik-h** [comment]
> @kumardeepakamd / @frederik-h can you coordinate?

@kumardeepakamd I have created a draft PR for the 2d operator: https://github.com/llvm/torch-mlir/pull/2693. I think the 1d operator is just a special case, i.e. it should probably be converted to the 2d operator, but it will still require separate testing etc.

**Comment by kumardeepakamd** [comment]
[AMD Official Use Only - General]

I am thinking I still take care of pad1d and will make use of pad2d work by @frederik<https://github.com/frederik-h>. Is that okay?

Sent from my T-Mobile 5G Device
Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by frederik-h** [comment]
@kumardeepakamd Is it ok to close this issue since https://github.com/llvm/torch-mlir/pull/2706 has been merged? Or is there anything else left to do?
