### ISSUE TITLE
LayerNormalization

### ISSUE THREAD

**Issue by AmosLewis** [nod-ai/SHARK-Turbine#325]
https://github.com/llvm/torch-mlir/pull/2716

**Comment by afalkenberg1** [comment]
Hmm I thought I did that ... maybe at the wrong place. Anyway thanks for the reminder

**Comment by afalkenberg1** [comment]
Can you assign it to me ? I think I still can not edit #215 ; oh by the way I did some updates including your feedback.

**Comment by AmosLewis** [comment]
> Can you assign it to me ? I think I still can not edit #215 ; oh by the way I did some updates including your feedback.

Just assign to you.

**Comment by afalkenberg1** [comment]
This issue is closed now ; Layernorm is merged.
