### ISSUE TITLE
GatherND

### ISSUE THREAD

**Issue by Shukla-Gaurav** [nod-ai/SHARK-Turbine#346]

**Comment by Shukla-Gaurav** [comment]
@rsuderman 
Hi Rob,
This is regarding the onnx.gatherND op support in torch-mlir.
https://onnx.ai/onnx/operators/onnx__GatherND.html#l-onnx-doc-gathernd
It looks a little complicated as it involves indexing multiple dimensions of the data using indices tensor at the same time.
I have an algorithm but it involves playing with indices values, like mapping indices_shape[-1] values to a single value.
for eg. 
assume batch_dims =0, indices shape is (3,4,2), data shape is (2,4,9,7)
1. reshape data to  (8,9,7) 
2. make indices of shape (3,4) by mapping indices_shape[-1] dim values to a single index value poining at corresponding location of data tensor. Since indices_shape[-1]=2, it will be kind of 2D to 1D mapping of values.
In this way I am trying to achieve indexing at axis=0 of data.
3. onnx.gather(data, indices, axis=0) will yield result of shape(3,4,9,7)

Can you help me figuring out a better approach for the same?

**Comment by vivekkhandelwal1** [comment]
Added https://github.com/llvm/torch-mlir/pull/2988.
