### ISSUE TITLE
Resize

### ISSUE THREAD

**Issue by AmosLewis** [nod-ai/SHARK-Turbine#358]
https://github.com/llvm/torch-mlir/pull/3013

**Comment by aldesilv** [comment]
import torch
import torch.nn.functional as F

# node = onnx.helper.make_node(
#            "Resize",
#            inputs=["X", "", "scales"],
#            outputs=["Y"],
#            mode="cubic",
#          )

# data = np.array(
#            [
#                        [
#                                        [
#                                               [1, 2, 3, 4],
#                                               [5, 6, 7, 8],
#                                               [9, 10, 11, 12],
#                                               [13, 14, 15, 16],
#                                     ]
#                       ]
#           ],
#                dtype=np.float32,
#                )

# scales = np.array([1.0, 1.0, 0.8, 0.8], dtype=np.float32)

# [[[[ 1.47119141  2.78125     4.08251953]
#    [ 6.71142578  8.02148438  9.32275391]
#    [11.91650391 13.2265625  14.52783203]]]]
# output = interpolate_nd(
#            data, lambda x, _: cubic_coeffs(x), scale_factors=scales
#            ).astype(np.float32)

# expect(
#            node,
#            inputs=[data, scales],
#            outputs=[output],
#            name="test_resize_downsample_scales_cubic",
#      )
a = torch.tensor([[[
 [1., 2., 3., 4.],
[5., 6., 7., 8.],
[9., 10., 11., 12.],
[13., 14., 15., 16.],
]]])

a_downsample = F.interpolate(a, scale_factor=[0.8, 0.8], mode='bicubic')
print(a_downsample)

**Comment by PhaneeshB** [comment]
There are onnx models being imported in SHARK-TestSuite that require 
`coordinate_transformation_mode = "half_pixel"` and `mode = "linear"`
`coordinate_transformation_mode = "asymmetric"` and `mode = "nearest"`

Here's the issue #616
