### ISSUE TITLE
MODEL: Verify SDXL Turbo full model correctness via ROCm

### ISSUE THREAD

**Issue by powderluv** [nod-ai/SHARK-Turbine#414]

**Comment by IanNod** [comment]
Has essentially the same success and issues as SDXL base:
  |    |CPU Compile | CPU Runtime | Vulkan Compile | Vulkan Runtime | ROCM Compile | ROCM Runtime
  :--:| :-------------:  | :-------------: | :----------------: | :-----------------: | :----------------: | :----------------:
  | clip1 | Good | Good | [Fail](https://gist.github.com/IanNod/12e23d00ce2a1388efdd5e90274aa9a9)| NA | Good | [gist](https://gist.github.com/IanNod/23a74b49621bc3a7cfd0583a31d2d965)
  | clip2 | Good | Good | [Fail](https://gist.github.com/IanNod/12e23d00ce2a1388efdd5e90274aa9a9) | NA | Good | [gist](https://gist.github.com/IanNod/23a74b49621bc3a7cfd0583a31d2d965)
  | unet | Good | Fail (possibly just fp16 vs fp32 casting issue) | Fail | NA | Fail | NA
  | vae | Good | Fail, all zeros output | [Fail](https://gist.github.com/IanNod/e5aca4432625544a0357b1445dfa0f9d) | NA | Good | [gist](https://gist.github.com/IanNod/23a74b49621bc3a7cfd0583a31d2d965)

**Comment by antiagainst** [comment]
Closing this one given that Turbo has the same model architecture so https://github.com/nod-ai/SHARK-Turbine/issues/412 is good in tracking.
