### ISSUE TITLE
KERNEL: land stop-gap prefetch pass

### ISSUE THREAD

**Issue by antiagainst** [nod-ai/SHARK-Turbine#432]

**Comment by antiagainst** [comment]
https://github.com/openxla/iree/pull/16375 for it.

**Comment by kuhar** [comment]
Current implementation: https://github.com/openxla/iree/tree/llvmgpu-prefetching

**Comment by Groverkss** [comment]
Fixed by https://github.com/openxla/iree/pull/16723
