### ISSUE TITLE
GRAPH: Lower PyTorch sdpa to linalg ext attention

### ISSUE THREAD

**Issue by antiagainst** [nod-ai/SHARK-Turbine#433]

**Comment by monorimet** [comment]
This is completed by https://github.com/openxla/iree/pull/16416 but there are some unrelated build failures for byo_llvm (related to llvm bump included in that patch)

https://github.com/llvm/torch-mlir/pull/2907 is already merged, the IREE patch simply enables the reduce-op-variants pass needed in the torch->tm_tensor flow in IREE (and bumps some versions)

**Comment by stellaraccident** [comment]
The byo problem is due to super old gcc incompatibility in an unrelated tool. I can have a look and fix it in the morning.

**Comment by antiagainst** [comment]
This is done now. So closing.
