### ISSUE TITLE
OnnxToTorch Celu Op

### ISSUE THREAD

**Issue by vivekkhandelwal1** [nod-ai/SHARK-Turbine#438]

**Comment by vivekkhandelwal1** [comment]
@alxader is working on this.

**Comment by kumardeepakamd** [comment]
@aldesilv if I recall right, this has been completed? If yes, could you kindly add enough tests in torch-mlir e2e, torch-mlir lit and e2eshark pytorch/operators and onnx./operators suite to make sure implementation is robust? Ping me if you need help with test creation.

**Comment by vivekkhandelwal1** [comment]
Support added: https://github.com/llvm/torch-mlir/pull/2920
