### ISSUE TITLE
SDXL clip2 compilation failure on ROCm

### ISSUE THREAD

**Issue by jinchen62** [nod-ai/SHARK-Turbine#446]
Failed to compile SDXL clip2 on ROCm, it exceeds the limit of shared memory.

>  error: 'func.func' op uses 327680 bytes of shared memory; exceeded the limit of 166912 bytes

clip2 mlir: https://storage.googleapis.com/shark_tank/jinchen/sdxl/sdxl_base_clip2.mlir
command: `iree-compile --iree-hal-target-backends=rocm --iree-rocm-link-bc=true --iree-rocm-target-chip=gfx90a --iree-rocm-bc-dir=/opt/rocm/amdgcn/bitcode sdxl_base_clip_2.mlir -o sdxl_base_clip_2.vmfb`
full error log: https://gist.github.com/jinchen62/bcfcb9d159a78d6dbaed5334a701ae17

Found that dispatches with matmul op failed including `matmul_transpose_b`, `batch_matmul_transpose_b` and `batch_matmul`, but showing a different error.

> error: 'iree_linalg_ext.set_encoding' op unhandled tensor operation

dispatch: https://gist.github.com/jinchen62/6b5941273573eaf0914f40b616ed058c
command: `iree-compile --iree-hal-target-backends=rocm --iree-rocm-link-bc=true --iree-rocm-target-chip=gfx90a --iree-rocm-bc-dir=/opt/rocm/amdgcn/bitcode sdxl_clip2_dispatch_517.mlir -o sdxl_clip2_dispatch_517.vmfb --mlir-print-ir-after-all 2> dump.mlir`

**Comment by Max191** [comment]
> Found that dispatches with matmul op failed including `matmul_transpose_b`, `batch_matmul_transpose_b` and `batch_matmul`, but showing a different error.
> 
> > error: 'iree_linalg_ext.set_encoding' op unhandled tensor operation`
> 
> dispatch: https://gist.github.com/jinchen62/6b5941273573eaf0914f40b616ed058c command: `iree-compile --iree-hal-target-backends=rocm --iree-rocm-link-bc=true --iree-rocm-target-chip=gfx90a --iree-rocm-bc-dir=/opt/rocm/amdgcn/bitcode sdxl_clip2_dispatch_517.mlir -o sdxl_clip2_dispatch_517.vmfb --mlir-print-ir-after-all 2> dump.mlir`

https://github.com/openxla/iree/pull/16429 will fix the `iree_linalg_ext.set_encoding` issue. It should also not be an issue in the model compilation. It will only cause the error when compiling the mlir with the function already exported.

**Comment by antiagainst** [comment]
> clip2 mlir: https://storage.googleapis.com/shark_tank/jinchen/sdxl/sdxl_base_clip2.mlir

Hi @jinchen62, this model is also different from the clip models we have in the playbook? Could you double check the input model?

**Comment by antiagainst** [comment]
> dispatch: https://gist.github.com/jinchen62/6b5941273573eaf0914f40b616ed058c

The issue is legit. Can be reproduced by just `iree-compile --compile-mode=hal-executable`. Looking at the dispatch, it's effectively a matmul with M=1, so a matvec. It goes down the warp reduction pipeline properly. But due to this large vector contraint [here](https://github.com/openxla/iree/blob/1ae8e95/compiler/src/iree/compiler/Codegen/LLVMGPU/Passes.cpp#L542) it does not vectorize.. That number was previously sort of random set to avoid vector level unrolling to blow up. Quite historical. Not sure it still holds so we should just drop it.

**Comment by jinchen62** [comment]
> > clip2 mlir: https://storage.googleapis.com/shark_tank/jinchen/sdxl/sdxl_base_clip2.mlir
> 
> Hi @jinchen62, this model is also different from the clip models we have in the playbook? Could you double check the input model?

@antiagainst I generated that IR by https://github.com/nod-ai/SHARK-Turbine/blob/ean-sd-fp16/models/turbine_models/custom_models/sdxl_inference/clip.py, and yes I just confirmed that it compiles fine now.
