### ISSUE TITLE
MODEL: Generate CLIP and VAE models preserving attention ops

### ISSUE THREAD

**Issue by antiagainst** [nod-ai/SHARK-Turbine#453]
We now have UNET models with attention op preserved. Need to do the same for other SDXL (Turbo) model parts--they also have attention ops. Please keep separate model mlir files like what we have right now for UNET, which makes it easier to compare.

**Comment by monorimet** [comment]
CLIP: the CLIPAttention layers are silently decomposed at the dynamo export level, as they don't have matches in the aten opset.

VAE: done

**Comment by antiagainst** [comment]
Thanks @monorimet! This is done now. Closing.
