### ISSUE TITLE
fx import creates 13 inputs vs 1 for pytorch and onnx

### ISSUE THREAD

**Issue by kumardeepakamd** [nod-ai/SHARK-Turbine#455]
for opt-125M, the issue is still there where for fximport it has 13 inputs vs pytorch and onnx having only one:
iree/runtime/src/iree/vm/invocation.c:95: INVALID_ARGUMENT; input list and function mismatch; expected 13 arguments but passed 1; invoking function 'main'; sync func @main(%input0: tensor<f32>, %input1: tensor<f32>, %input2: tensor<f32>, %input3: tensor<f32>, %input4: tensor<f32>, %input5: tensor<f32>, %input6: tensor<f32>, %input7: tensor<f32>, %input8: tensor<f32>, %input9: tensor<f32>, %input10: tensor<f32>, %input11: tensor<f32>, %input12: tensor<1x8xi64>) -> (%output0: tensor<1x8x50272xf32>, %output1: tensor<1x12x8x64xf32>, %output2: tensor<1x12x8x64xf32>, %output3: tensor<1x12x8x64xf32>, %output4: tensor<1x12x8x64xf32>, %output5: tensor<1x12x8x64xf32>, %output6: tensor<1x12x8x64xf32>, %output7: tensor<1x12x8x64xf32>, %output8: tensor<1x12x8x64xf32>, %output9: tensor<1x12x8x64xf32>, %output10: tensor<1x12x8x64xf32>, %output11: tensor<1x12x8x64xf32>, %output12: tensor<1x12x8x64xf32>, %output13: tensor<1x12x8x64xf32>, %output14: tensor<1x12x8x64xf32>, %output15: tensor<1x12x8x64xf32>, %output16: tensor<1x12x8x64xf32>, %output17: tensor<1x12x8x64xf32>, %output18: tensor<1x12x8x64xf32>, %output19: tensor<1x12x8x64xf32>, %output20: tensor<1x12x8x64xf32>, %output21: tensor<1x12x8x64xf32>, %output22: tensor<1x12x8x64xf32>, %output23: tensor<1x12x8x64xf32>, %output24: tensor<1x12x8x64xf32>)

STR:
git clone https://github.com/nod-ai/SHARK-TestSuite.git
cd e2eshark
Read README.md to setup 

python run.py --torchmlirbuild /proj/gdba/kumar/nod/torch-mlir/build --ireebuild /proj/gdba/kumar/nod/mainireee/iree-build --hfhome /proj/gdba/kumar/HF_HOME  --mode direct -r test-direct-fp32 --tests pytorch/models/opt-125M 

cd test-direct-fp32/pytorch/models/opt-125M

Examine inference.log

**Comment by stellaraccident** [comment]
Most likely pytorch version related. There have been fixes to the upstream ExportedProgram API, that while good, have made it hard to ensure it is working on all nightlies. There was a range where it was just broken to.

See:
https://github.com/llvm/torch-mlir/commit/3e836d8dad551b6e5302de1b84840b90ee039c83

https://github.com/llvm/torch-mlir/commit/5253282c55546d19e00f8b244c2da74cf76c8486

**Comment by saienduri** [comment]
Looks like kd was able to resolve this with local updates :). @stellaraccident I was wondering if we can switch to using your fx_import that deals with mutable semantics in e2e test suite. I've tested and it works fine with updated nightly, but I just wanted to check with you because it is marked as "experimental_support_mutation".

**Comment by stellaraccident** [comment]
It just landed on Thursday, but it is works for you and you can use the bleeding edge nightlies, should be fine.

**Comment by kumardeepakamd** [comment]
Oh, my bad, I needed to rebuild torch mlir wheel and install it. It works. Hooray!! Thank you!
