### ISSUE TITLE
KERNEL: Check matmul CodeGen configurations

### ISSUE THREAD

**Issue by antiagainst** [nod-ai/SHARK-Turbine#491]
Right now for matmul in SDXL we are just using a default heuristics to get started. Eventually we want procedures to autotune/search for the most performant configuration. But for now we can do it a bit manually for the matmul problem shapes we care about in SDXL. Specifically, take a trace profile of the current UNET, check the top time consuming matmuls, find their dispatches `_benchmark.mlir` files (from `--iree-hal-executable-dump-benchmarks-to=` when compiling the model), and tweak the `iree_codegen.translation_info` and `workgroup_size` and `tile_sizes` inside, recompile and benchmark.

**Comment by kuhar** [comment]
Landed in IREE main: https://github.com/openxla/iree/pull/16938. At the end simple transpose performed better than more complicated traversal patterns.

**Comment by kuhar** [comment]
Done, implemented in the sprint repo: https://github.com/nod-ai/2024-q1-sdxl-sprint/tree/main/mmt_tuning.
Opened an umbrella issue against IREE to implement this properly: https://github.com/openxla/iree/issues/16952.
