### ISSUE TITLE
Conv rocm numeric issue

### ISSUE THREAD

**Issue by IanNod** [nod-ai/SHARK-Turbine#498]
The 2nd conv in the torch IR of SDXL unet for fp16 rocm is providing different results than the verified cpu fp32 version. Comparison of the tensor values from a tensor trace can be found in the following gist

https://gist.github.com/IanNod/72b4b13198ced90f3e3ef76ba25f094c

The conv in question is:
    %148 = torch.aten.convolution %140, %142, %143, %144, %145, %146, %false_146, %147, %int1_149 : !torch.vtensor<[2,320,128,128],f16>, !torch.vtensor<[320,320,3,3],f16>, !torch.vtensor<[320],f16>, !torch.list<int>, !torch.list<int>, !torch.list<int>, !torch.bool, !torch.list<int>, !torch.int -> !torch.vtensor<[2,320,128,128],f16>  
    
 Commands to compile and run:
 Rocm:
compile: tools/iree-compile \
    --iree-hal-target-backends=rocm \
    --iree-rocm-target-chip=gfx940 \
    --iree-rocm-link-bc=true \
    --iree-rocm-bc-dir=/opt/rocm/amdgcn/bitcode \
    --iree-global-opt-propagate-transposes=true \
    --iree-opt-outer-dim-concat=true \
    --iree-opt-const-eval=false \
    --iree-codegen-gpu-native-math-precision=true \
    --iree-rocm-waves-per-eu=2 \
    --iree-preprocessing-pass-pipeline="builtin.module(iree-preprocessing-transpose-convolution-pipeline)" \
    --iree-codegen-transform-dialect-library=attention_mfma_transform_64_spec.mlir \
    ../SHARK-Turbine/stable_diffusion_xl_base_1_0_64_1024x1024_fp16_unet.mlir -o rocm.vmfb
    
    run:
    tools/iree-run-module \
    --device=rocm --module=rocm.vmfb \
    --parameters=model=../SDXL1_unet.safetensors  \
    --function=main \
    --input=1x4x128x128xf16 --input=1xf16 --input=2x64x2048xf16 \
    --input=2x1280xf16 --input=2x6xf16 --input=1xf16 &> rocm_out.txt

cpu:
compile: iree-compile ../SHARK-Turbine/decomp_sdpa.mlir --iree-input-type=torch --iree-vm-bytecode-module-output-format=flatbuffer-binary --iree-hal-target-backends=llvm-cpu --mlir-print-debuginfo --mlir-print-op-on-diagnostic=false --iree-opt-strip-assertions=true --verify=false --iree-llvmcpu-target-triple=x86_64-unknown-unknown-eabi-elf --iree-llvmcpu-target-cpu-features=host --iree-llvmcpu-fail-on-out-of-bounds-stack-allocation=false --iree-llvmcpu-distribution-size=32 --iree-opt-const-expr-hoisting=False --iree-codegen-linalg-max-constant-fold-elements=9223372036854775807 -o cpu.vmfb

    run:
    tools/iree-run-module \
    --device=local-task --module=cpu.vmfb \
    --parameters=model=../SDXL1_unet.safetensors  \
    --function=main \
    --input=1x4x128x128xf16 --input=1xf16 --input=2x64x2048xf16 \
    --input=2x1280xf16 --input=2x6xf16 --input=1xf16 &> cpu_out.txt

**Comment by PhaneeshB** [comment]
Similar Findings for the first conv dropping the match rate by ~50% on rocm compared to Pytorch f16 / f32
the inputs to the conv are same 

```
-----------------------------------------------------------
Compare f16 pytorch to f16 rocm
pct correct : (5869086/10485760) (55.97196578979492%)
Max error: 2.54
largest Error : 2.5390625
-----------------------------------------------------------
Compare f32 pytorch to f16->f32 rocm
pct correct : (5868733/10485760) (55.968599319458015%)
Max error: 2.5404515
largest Error : 2.5404515266418457
-----------------------------------------------------------
Compare f32 pytorch to f16->f32 pytorch
pct correct : (10485760/10485760) (100.0%)
Max error: 0.0009834766
largest Error : 0.0009834766387939453
-----------------------------------------------------------
```
[Fx GraphModules for fp32 and fp16 ](https://gist.github.com/PhaneeshB/6527b7a445ccb8b095d433e58647ed7c)

[Conv Dispatch ](https://gist.github.com/PhaneeshB/21295917300859b9144b2c454bd2dcef)

**Comment by IanNod** [comment]
Adding --iree-codegen-llvmgpu-use-vector-distribution flag and PR https://github.com/openxla/iree/commit/62da59b14cc2cd087bfd4def980925a424061625 looks to have improved this conv shape but now diverging at a later conv (6th on in the unet mlir)

%338 = torch.aten.convolution %330, %332, %333, %334, %335, %336, %false_327, %337, %int1_330 : !torch.vtensor<[2,320,128,128],f16>, !torch.vtensor<[320,320,3,3],f16>, !torch.vtensor<[320],f16>, !torch.list<int>, !torch.list<int>, !torch.list<int>, !torch.bool, !torch.list<int>, !torch.int -> !torch.vtensor<[2,320,64,64],f16>
