### ISSUE TITLE
KERNEL: Try out SplitK for matmul with large K

### ISSUE THREAD

**Issue by antiagainst** [nod-ai/SHARK-Turbine#510]

**Comment by kuhar** [comment]
We tried that and the overhead of an extra kernel wasn't worth it. We may need to do the final accumulation in the same kernel to make this performant, e.g., using float atomics. Prototype implementations: https://github.com/kuhar/iree/tree/splitk-attr and https://github.com/kuhar/iree/tree/splitk-flag.
