### ISSUE TITLE
[matmul] Support better instruction scheduling for matmul

### ISSUE THREAD

**Issue by antiagainst** [nod-ai/SHARK-Turbine#515]
* Better overlap compute and memory instructions in matmul

**Comment by Groverkss** [comment]
Some things i looked at for this before:

https://llvm.org/doxygen/AMDGPUIGroupLP_8cpp_source.html
https://reviews.llvm.org/D149773

In my opinion, this should be done at AMDGPU llvm backend level.

**Comment by antiagainst** [comment]
Update 5/28: scheduling barriers does help in controlling instruction scheduling.

**Comment by antiagainst** [comment]
We have tkf delivering gains now. closing.
