### ISSUE TITLE
SoftPlus assert hasSizes failure with static shapes

### ISSUE THREAD

**Issue by IanNod** [nod-ai/SHARK-Turbine#534]
Model is failing this assert https://github.com/llvm/torch-mlir/blob/895ea8663a7d350a0c46254b138018e0328a865f/include/torch-mlir/Dialect/Torch/IR/TorchTypes.h#L61C4-L62C39

when decomposing SoftPlus in DecomposeComplexOps with all cases of the op having static shapes: https://github.com/llvm/torch-mlir/blob/895ea8663a7d350a0c46254b138018e0328a865f/lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp#L3851C55-L3851C75

The IR dump in question can be found here:
[before_decompose_complex_operations.txt](https://github.com/nod-ai/SHARK-Turbine/files/14643895/before_decompose_complex_operations.txt)

**Comment by dan-garvey** [comment]
not sure if it is related but this `unk` dtype looks pretty weird to me, especially when its a copy of an f32? 
```
    %242 = torch.tensor_static_info_cast %arg1 : !torch.vtensor<[24,1,1536,16],f32> to !torch.vtensor
    %243 = torch.copy.to_tensor %242 : !torch.tensor
    %244 = torch.tensor_static_info_cast %arg2 : !torch.vtensor<[24,1,1536,3],f32> to !torch.vtensor
    %245 = torch.copy.to_tensor %244 : !torch.tensor
    %246 = torch.aten.embedding %241, %arg0, %int-1, %false, %false : !torch.vtensor<[50280,768],f32>, !torch.vtensor<[1],si64>, !torch.int, !torch.bool, !torch.bool -> !torch.vtensor<[1,768],f32>
    %247 = torch.aten.select.int %243, %int0, %int0 : !torch.tensor, !torch.int, !torch.int -> !torch.tensor<[1,1536,16],unk>
```

**Comment by dan-garvey** [comment]
you've got a bunch of vtensors with no shapes too, which is what is probably triggering that assert

**Comment by gabeweisz** [comment]
This is not using turbine, this is a regular torch model using the 1.0 Shark branch. If there is a branch using turbine that is stable enough to try I can try that - just point me to the right branch

**Comment by gabeweisz** [comment]
Here is a minimal repro:
run build-debug/bin/torch-mlir-opt  --torchscript-module-to-torch-backend-pipeline ~/MambaLMFunctional_1layer.mlir
in torch-mlir, I tried commit 6b3a7d07c2c76f5e8437ff4e88110899621557b9
[stderr.txt](https://github.com/nod-ai/SHARK-Turbine/files/14661287/stderr.txt)
[MambaLMFunctional_1layer.mlir.txt](https://github.com/nod-ai/SHARK-Turbine/files/14661298/MambaLMFunctional_1layer.mlir.txt)

**Comment by stellaraccident** [comment]
Yeah, torch dynamo based export can't produce issues like this because it always has shapes and types defined. The old TorchScript path starts without either and tries to get them back. It's really fragile and basically unsupported by pytorch or torch-mlir at this point.

Anything that says torchscript in it is on life support... :/

**Comment by gabeweisz** [comment]
I see - I don't care if I use torch dynamo or torchscript or something totally different. I have a PyTorch model and I want to get it into the Shark runtime. What mechanism should I be using? Should I be using SharkImporter or something else? Should I be using the SHARK-1.0 branch or a different branch? The only reference I have is [this ](https://github.com/nod-ai/SHARK?tab=readme-ov-file#shark-inference-api) page on the Shark GitHub.

**Comment by stellaraccident** [comment]
@monorimet I'm not exactly sure how to answer these questions at the application level.

Most of us who are doing development are using Turbine and Torch APIs directly. "Shark Runtime" is a collection of technologies, and you are interesecting a few of them at old versions.

Here are the docs on the core APIs for compiling torch models: https://iree.dev/guides/ml-frameworks/pytorch/#exporting-functions

The shark Runtime has a number of things which tie this together and expose for various tasks. Ean can help guide at that level.

**Comment by gabeweisz** [comment]
Thanks, I will try using the APIs referenced above. We can close this issue (I'd do it myself but don't seem to have the ability to do so) and I will reach out in a new thread if I need additional assistance
