### ISSUE TITLE
questions about CompiledModule argument 

### ISSUE THREAD

**Issue by bailuan** [nod-ai/SHARK-Turbine#544]
Hi, guys.
Recently I am testing sd_test.py in turbine, `export_clip_model` , `export_unet_model`, `export_vae_model` could run successfully when argument is `vmfb`, but it saved a torch ir and regard it as iree's input.
But actually I don't want this torch ir, I want the IR with `linalg`, just like the old version shark-turbine did (via "torch-to-iree" in cpu.py).
Why turbine doesn't support linalg IR generated ? I remember yesterday when I use a little old version, I can set the argument of "export_clip_model" with `linalg`, it can generate a right linalg IR, although the `export_vae_model` with `linalg` would be error.
The error is here [https://github.com/nod-ai/SHARK-Turbine/issues/532#issuecomment-2006186275](url)
So I have two questions:
1. why deprecate the feature which can generate linalg by turbine;
2. what should I do if I really need the linalg ir.
Thanks a lot.

**Comment by stellaraccident** [comment]
It's not deprecated but a different default. The torch IR is more stable as it structurally hardly ever changes. So we often persist that as an intermediate artifact. Linalg is an internal IR, and while it is fine to use, there are a lot of implementation details encoded in that form.

The torch-to-iree pass is still there but it does a number of other things too. It has linalg ops but it has other iree ops in it too -- we made no representation that it is "pure" linalg in any meaningful way. We didn't so much remove a feature but optimized our use.

With that said, passes exist which do the thing you likely want. We just need to expose the option to invoke them. Or give you a python incantation to self serve. What exact code are you running? (There are multiple entry points and I don't track all of the ways in)

**Comment by bailuan** [comment]
I got that, thanks.
I am testing this : SHARK-Turbine/models/turbine_models/tests/sd_test.py

**Comment by stellaraccident** [comment]
I think this is the pipeline you will actually want: https://github.com/llvm/torch-mlir/blob/3a56714bffae51c3ba12dd44c4a13fbaf9d0fed3/projects/pt1/python/torch_mlir/torchscript.py#L293

The torch-to-iree pipeline emits quite a bit of iree specific ops at the boundaries, whereas this one is the pure pipeline from upstream. I think it is included in the compiler. I need to look up the exact incantation when I'm at my computer.

**Comment by bailuan** [comment]
> I think this is the pipeline you will actually want: https://github.com/llvm/torch-mlir/blob/3a56714bffae51c3ba12dd44c4a13fbaf9d0fed3/projects/pt1/python/torch_mlir/torchscript.py#L293
> 
> The torch-to-iree pipeline emits quite a bit of iree specific ops at the boundaries, whereas this one is the pure pipeline from upstream. I think it is included in the compiler. I need to look up the exact incantation when I'm at my computer.

Thanks, I will try torch-mlir. Also, please share the  incantation with me if you are ok.

**Comment by renxida** [comment]
```
        CompiledModule.run_pass_pipeline(
            module,
            "builtin.module(torch-backend-to-linalg-on-tensors-backend-pipeline)",
            enable_ir_printing=True)
```

Is probably the incantation you need if you're trying to do it in python. You can find the impl for `run_pass_pipeline()` here: https://github.com/nod-ai/SHARK-Turbine/blob/main/core/shark_turbine/aot/compiled_module.py#L454

Feel free to friend me on discord: @xida_ren . happy to call to help figure this out!

**Comment by bailuan** [comment]
Thanks @renxida , it did work!
`linalg_str = str(CompiledModule.run_pass_pipeline(
            inst,
            "builtin.module(torch-backend-to-linalg-on-tensors-backend-pipeline)",
            enable_ir_printing=False))`
i add above code into vae.py, testExportVaeModelDecode succeed, but testExportVaeModelEncode failed. 
error looks like:
`iree.compiler._mlir_libs._site_initialize.<locals>.MLIRError: Failure while executing pass pipeline:
error: "<eval_with_key>.0 from /workspace/bailuan/20231221_pytorch_install/pytorch/torch/fx/experimental/proxy_tensor.py:477 in wrapped":320:0: failed to legalize operation 'torch.constant.int'
 note: "<eval_with_key>.0 from /workspace/bailuan/20231221_pytorch_install/pytorch/torch/fx/experimental/proxy_tensor.py:477 in wrapped":320:0: see current operation: %3 = "torch.constant.int"() <{value = -1 : i64}> : () -> !torch.int`
Did someone test testExportVaeModelEncode like me? it can run the test pipeline successful, but can't run through "torch-backend-to-linalg-on-tensors-backend-pipeline", it is very strange because I think it have to go through the torch-to-linalg if it want compile out the vmfb.
Some advice?

**Comment by bailuan** [comment]
> Thanks @renxida , it did work! `linalg_str = str(CompiledModule.run_pass_pipeline( inst, "builtin.module(torch-backend-to-linalg-on-tensors-backend-pipeline)", enable_ir_printing=False))` i add above code into vae.py, testExportVaeModelDecode succeed, but testExportVaeModelEncode failed. error looks like: `iree.compiler._mlir_libs._site_initialize.<locals>.MLIRError: Failure while executing pass pipeline: error: "<eval_with_key>.0 from /workspace/bailuan/20231221_pytorch_install/pytorch/torch/fx/experimental/proxy_tensor.py:477 in wrapped":320:0: failed to legalize operation 'torch.constant.int' note: "<eval_with_key>.0 from /workspace/bailuan/20231221_pytorch_install/pytorch/torch/fx/experimental/proxy_tensor.py:477 in wrapped":320:0: see current operation: %3 = "torch.constant.int"() <{value = -1 : i64}> : () -> !torch.int` Did someone test testExportVaeModelEncode like me? it can run the test pipeline successful, but can't run through "torch-backend-to-linalg-on-tensors-backend-pipeline", it is very strange because I think it have to go through the torch-to-linalg if it want compile out the vmfb. Some advice?

use "torch-to-iree" works fine.
