### ISSUE TITLE
"DiagonalModule_basic",

### ISSUE THREAD

**Issue by zjgarvey** [nod-ai/SHARK-Turbine#553]

**Comment by zjgarvey** [comment]
```
Unexpected outcome summary: (onnx)

****** Failed tests - 1 tests
    FAIL - "DiagonalModule_basic"
        Compilation error: Traceback (most recent call last):
          File "/home/zjgar/code/torch-mlir/build/tools/torch-mlir/python_packages/torch_mlir/torch_mlir_e2e_test/framework.py", line 298, in compile_and_run_test
            compiled = config.compile(test.program_factory())
          File "/home/zjgar/code/torch-mlir/build/tools/torch-mlir/python_packages/torch_mlir/torch_mlir_e2e_test/configs/onnx_backend.py", line 88, in compile
            compiled_module = self.backend.compile(onnx_module)
          File "/home/zjgar/code/torch-mlir/build/tools/torch-mlir/python_packages/torch_mlir/torch_mlir_e2e_test/onnx_backends/linalg_on_tensors.py", line 55, in compile
            run_pipeline_with_repro_report(
          File "/home/zjgar/code/torch-mlir/build/tools/torch-mlir/python_packages/torch_mlir/torch_mlir/compiler_utils.py", line 73, in run_pipeline_with_repro_report
            raise TorchMlirCompilerError(trimmed_message) from None
        torch_mlir.compiler_utils.TorchMlirCompilerError: Lowering TorchFX IR -> Torch Backend IR failed with the following diagnostics:


        python exception: Failure while executing pass pipeline:
        error: "/EyeLike": failed to legalize operation 'torch.operator' that was explicitly marked illegal
        note: "/EyeLike": see current operation: %24 = "torch.operator"(%23) <{name = "onnx.EyeLike"}> {torch.onnx.k = 0 : si64} : (!torch.vtensor<[?,?],f32>) -> !torch.vtensor<[?,?],f32>

        For Torch-MLIR developers, the error can be reproduced with:
        $ torch-mlir-opt -pass-pipeline='builtin.module(torch-lower-to-backend-contract{backend-legal-ops=aten.flatten.using_ints,aten.adaptive_avg_pool1d,aten.unflatten.int})' /tmp/UnnammedModule.mlir
        Add '-mlir-print-ir-after-all -mlir-disable-threading' to get the IR dump for debugging purpose.
```

@jinchen62 Is this related to your EyeLike work? Let me know if you want another pair of eyes on the problems you are having (pun intended).

**Comment by jinchen62** [comment]
Seems here is failing to lower onnx.eyelike op, I can expect that cuz https://github.com/llvm/torch-mlir/pull/2994 is not landed yet. My issue is about dealing with the onnx.eyelike op with dynamic shape. If that is not your case and you cherry pick my pr, it's supposed to be lowered.

**Comment by zjgarvey** [comment]
> Seems here is failing to lower onnx.eyelike op, I can expect that cuz [llvm/torch-mlir#2994](https://github.com/llvm/torch-mlir/pull/2994) is not landed yet. My issue is about dealing with the onnx.eyelike op with dynamic shape. If that is not your case and you cherry pick my pr, it's supposed to be lowered.

I took a look through your PR, and yeah I would need dynamic dims supported to unblock this. I tried to see how dynamic dims might work, but it could be a bit tricky to add given the constraints on AtenEyeMOp's decomposition (see the note about AtenDiagEmbedOp in my review of your PR). Let me know if you want to brainstorm about it together sometime.

**Comment by jinchen62** [comment]
> > Seems here is failing to lower onnx.eyelike op, I can expect that cuz [llvm/torch-mlir#2994](https://github.com/llvm/torch-mlir/pull/2994) is not landed yet. My issue is about dealing with the onnx.eyelike op with dynamic shape. If that is not your case and you cherry pick my pr, it's supposed to be lowered.
> 
> I took a look through your PR, and yeah I would need dynamic dims supported to unblock this. I tried to see how dynamic dims might work, but it could be a bit tricky to add given the constraints on AtenEyeMOp's decomposition (see the note about AtenDiagEmbedOp in my review of your PR). Let me know if you want to brainstorm about it together sometime.

I haven't really worked on that PR this week. Rob said it's not a good idea to use aten.cat so I would need to redesign it. Yeah let's meet tmr with Rob to figure out the solution of dynamic shape. I remember you also faced some issues about dynamic shape, it would be helpful to co-hack this with your understandings.

**Comment by zjgarvey** [comment]
Now related to onnx.if failure.
