### ISSUE TITLE
ONNX opset version

### ISSUE THREAD

**Issue by saienduri** [nod-ai/SHARK-Turbine#570]
We are seeing these issues related to opset version (onnx to torch support needed) in these models (llama2-7b-GPTQ, opt-125m-gptq). Repro instructions can be found [here](https://github.com/nod-ai/SHARK-Turbine/issues/564):

```
torch.onnx.errors.UnsupportedOperatorError: Exporting the operator 'aten::bitwise_right_shift' to ONNX opset version 17 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub: https://github.com/pytorch/pytorch/issues.
```

**Comment by AmosLewis** [comment]
This looks like a pytorch issue, not the torch-mlir issues

**Comment by zjgarvey** [comment]
I got the pytorch PR for this merged here [https://github.com/pytorch/pytorch/pull/126229](https://github.com/pytorch/pytorch/pull/126229), so I'm going to close this issue.
