### ISSUE TITLE
OnnxToLinalg AveragePool Failing

### ISSUE THREAD

**Issue by vivekkhandelwal1** [nod-ai/SHARK-Turbine#582]

**Comment by vivekkhandelwal1** [comment]
https://github.com/llvm/torch-mlir/pull/3076

**Comment by renxida** [comment]
Looks like the pr merged

**Comment by AmosLewis** [comment]
https://gist.github.com/jinchen62/3ef667ee61425e2f3a0bea77c78d10db

**Comment by AmosLewis** [comment]
turned out to be a torch_mlir.tools.import_onnx misses shape inference isssue https://github.com/llvm/torch-mlir/issues/3593
