### ISSUE TITLE
torch.operator "onnx.Expand" error: failed to legalize operation

### ISSUE THREAD

**Issue by afalkenberg1** [nod-ai/SHARK-Turbine#598]
https://github.com/nod-ai/SHARK-Turbine/issues/636
RAFT_vaiq_int8.default.torch-onnx.mlir:2045:13: error: failed to legalize operation 'torch.operator' that was explicitly marked illegal
    %2041 = torch.operator "onnx.Expand"(%2002, %2040) : (!torch.vtensor<[1,2,?,?],f32>, !torch.vtensor<[?],si64>) -> !torch.vtensor<[],f32>
            ^
RAFT_vaiq_int8.default.torch-onnx.mlir:2045:13: note: see current operation: %7506 = "torch.operator"(%7142, %7505) <{name = "onnx.Expand"}> : (!torch.vtensor<[1,2,?,?],f32>, !torch.vtensor<[?],si64>) -> !torch.vtensor<[],f32>

**Comment by AmosLewis** [comment]
#636
