### ISSUE TITLE
[e2e][onnx][model] onnx.Expand

### ISSUE THREAD

**Issue by AmosLewis** [nod-ai/SHARK-Turbine#636]
Signature to be supported in [RAFT_vaiq_int8 model](https://github.com/nod-ai/SHARK-TestSuite/issues/182)

`%2041 = torch.operator "onnx.Expand"(%2002, %2040) : (!torch.vtensor<[1,2,?,?],f32>, !torch.vtensor<[?],si64>) -> !torch.vtensor<[],f32> 
`

The following signature also exist in RAFT_vaiq_int8 model, but it should have been supported by current onnx expand implementation.
`%2062 = torch.operator "onnx.Expand"(%2061, %2058) : (!torch.vtensor<[?,?],si64>, !torch.vtensor<[2],si64>) -> !torch.vtensor<[?,?],si64> 
`

To repeat this error:
```
torch-mlir-opt -convert-torch-onnx-to-torch ./RAFT_vaiq_int8.default.torch-onnx.mlir 
./RAFT_vaiq_int8.default.torch-onnx.mlir:2045:13: error: failed to legalize operation 'torch.operator' that was explicitly marked illegal
    %2041 = torch.operator "onnx.Expand"(%2002, %2040) : (!torch.vtensor<[1,2,?,?],f32>, !torch.vtensor<[?],si64>) -> !torch.vtensor<[],f32> 
            ^
./RAFT_vaiq_int8.default.torch-onnx.mlir:2045:13: note: see current operation: %7506 = "torch.operator"(%7142, %7505) <{name = "onnx.Expand"}> : (!torch.vtensor<[1,2,?,?],f32>, !torch.vtensor<[?],si64>) -> !torch.vtensor<[],f32>
```

**Comment by zjgarvey** [comment]
Maybe this is an issue with the importer?

Relevant lines of imported IR:

```MLIR
    %2039 = torch.operator "onnx.Shape"(%2011) : (!torch.vtensor<[4],si64>) -> !torch.vtensor<[1],si64> 
    %2040 = torch.operator "onnx.ConstantOfShape"(%2039) {torch.onnx.value = dense_resource<__1071> : tensor<1xsi64>} : (!torch.vtensor<[1],si64>) -> !torch.vtensor<[?],si64> 
    %2041 = torch.operator "onnx.Expand"(%2002, %2040) : (!torch.vtensor<[1,2,?,?],f32>, !torch.vtensor<[?],si64>) -> !torch.vtensor<[],f32> 
{-#
  dialect_resources: {
    builtin: {
      __1071: "0x080000000100000000000000"
    }
  }
#-}
```

I tried updating the opset version to see if there is any new shape inference for these ops, but still encountered the same issue.

It seems like a weird expand anyway, unless _1071 actually represents 2, and the dynamic dims of %2002 are actually either 1 or 2.

**Comment by zjgarvey** [comment]
I looks like I am able to unblock this issue with the change in [torch-mlir PR#3280](https://github.com/llvm/torch-mlir/pull/3280).

I'm not sure if there is any reason not to include data propogation with onnx shape inference. If there is some reason to generally avoid using it, I can change it to a command-line flag for the onnx importer.
