### ISSUE TITLE
torch.aten.convolution to linalg

### ISSUE THREAD

**Issue by AmosLewis** [nod-ai/SHARK-Turbine#642]
Find this issue in https://github.com/nod-ai/SHARK-TestSuite/issues/189
Failed op in [u-net_brain_mri_vaiq_int8.default.onnx.torch.elide.mlir](https://gist.github.com/AmosLewis/cb9d7a443e66997a57e2297cf571293a#file-u-net_brain_mri_vaiq_int8-default-onnx-torch-elide-mlir)

Failed op signature
`%221 = torch.aten.convolution %212, %216, %220, %80, %59, %58, %true, %59, %int1 : !torch.vtensor<[32,512,16,16],f32>, !torch.vtensor<[512,256,2,2],f32>, !torch.vtensor<[256],f32>, !torch.list<int>, !torch.list<int>, !torch.list<int>, !torch.bool, !torch.list<int>, !torch.int -> !torch.vtensor<[32,256,32,32],f32>`

To repeat the error
```
(mlir_venv) ➜  u-net_brain_mri_vaiq_int8 git:(reduceprod) ✗ torch-mlir-opt --torch-backend-to-linalg-on-tensors-backend-pipeline u-net_brain_mri_vaiq_int8.default.onnx.torch.mlir 
u-net_brain_mri_vaiq_int8.default.onnx.torch.mlir:238:12: error: failed to legalize operation 'torch.aten.convolution' that was explicitly marked illegal
    %221 = torch.aten.convolution %212, %216, %220, %80, %59, %58, %true, %59, %int1 : !torch.vtensor<[32,512,16,16],f32>, !torch.vtensor<[512,256,2,2],f32>, !torch.vtensor<[256],f32>, !torch.list<int>, !torch.list<int>, !torch.list<int>, !torch.bool, !torch.list<int>, !torch.int -> !torch.vtensor<[32,256,32,32],f32>
```

**Comment by zjgarvey** [comment]
I think I'm going to pick this up if no one else wants to dig into the quantization support issues. 

If someone wants to take this off of my hands, let me know. It might take a day or two for me to start.

**Comment by zjgarvey** [comment]
Fails due to transposed convolutions not-yet implementing non-fp type transposes. I'll dig into this and see if I can make it work.

**Comment by zjgarvey** [comment]
[torch-mlir PR #3240](https://github.com/llvm/torch-mlir/pull/3240)
