### ISSUE TITLE
torch.aten.remainder.Tensor

### ISSUE THREAD

**Issue by kobeliu85** [nod-ai/SHARK-Turbine#661]

**Comment by renxida** [comment]
1. fork & make branch
2. write a mlir test case (lit test)
3. use torch-mlir-opt to attempt to lower it and demonstrate that it fails
4. write lowering until lit test works
5. write end to end test
6. fix until e2e test works
7. @renxida for review
8. merge
9. celebrate

**Comment by vivekkhandelwal1** [comment]
Op implemented.
