### ISSUE TITLE
[attention] Extend attention to fuse transpose

### ISSUE THREAD

**Issue by antiagainst** [nod-ai/SHARK-Turbine#669]

**Comment by antiagainst** [comment]
Update 5/22: patch https://github.com/iree-org/iree/pull/17408 out; needing review.

**Comment by Groverkss** [comment]
Plan to finish it this week (Before Jun 7):

4 Jun: Land online attention (https://github.com/iree-org/iree/pull/17536)
5 Jun: Create transform script using online_attention for MFMA
6 Jun: Add indexing_maps to attention op
7 Jun: Fusions

**Comment by raikonenfnu** [comment]
Hey guys, quick update

1. Indexing attention (https://github.com/iree-org/iree/pull/17864) has landed
2. CastTypeOFitMMA support for TD pipeline (https://github.com/iree-org/iree/pull/17884) is up
3. transfer_write distribution for non contiguous indexing map (https://github.com/iree-org/iree/pull/17895) is up

Once 2. and 3. and https://github.com/iree-org/iree/commit/d2ca77402becf4c6476893845ba96116b61df9c1 is landed on main, we should be able to handle/compile fused attn-transpose.

**Comment by antiagainst** [comment]
Awesome. All 3 pull requests are in. Can you send out the last piece?

**Comment by raikonenfnu** [comment]
> Awesome. All 3 pull requests are in. Can you send out the last piece?

Hey Lei, I think @MaheshRavishankar is en route to pushing that one in! :)

**Comment by MaheshRavishankar** [comment]
I can send it in early next week.

**Comment by raikonenfnu** [comment]
I also pushed up/updated the spec mlir to find k2 correctly ([link](https://github.com/nod-ai/sdxl-scripts/commit/821b89d555d2d9e85ab9bcdf9432627b6b87a007)). I tested compiling on the fusion-preprocessing test MLIR [(here)](https://gist.github.com/raikonenfnu/ba681b3ede71fbf1d47d160365d44f62) and was able to get a vmfb out. 

The gist above is slightly different from the test in where we make the scale constant here. It fails on vector distribution if scale is not constant.

compile command:
```
~/nod/iree-build-notrace/tools/iree-compile constant_transpose_fusion.mlir --iree-hal-target-backends=rocm --iree-rocm-target-chip=gfx942 --iree-global-opt-propagate-transposes=true --iree-opt-outer-dim-concat=true --iree-opt-const-eval=false --iree-opt-data-tiling=false --iree-rocm-waves-per-eu=2 --iree-vm-target-truncate-unsupported-floats --iree-codegen-llvmgpu-use-vector-distribution --iree-codegen-gpu-native-math-precision=true --iree-flow-enable-aggressive-fusion -o attention.vmfb --iree-codegen-transform-dialect-library=attention_and_matmul_spec.mlir
```

**Comment by raikonenfnu** [comment]
FYI I also tested the attention-transpose-fusion vmfb numerics on normal random numbers (0.0, 1.0) against torch, seems like we have good numerics there :)
<img width="633" alt="numerics_test" src="https://github.com/user-attachments/assets/89e58143-aeb5-48b8-b329-26ebba4009d1">


Starting IR, compile command, data generator can all be found in https://gist.github.com/raikonenfnu/973b4d91e4378702ce4b4496d732cb57

Needed to update the shape from the original fusion-preprocessing test a little bit since the fastest dim for Q,K,V needs to be the same to run on pytorch.
