### ISSUE TITLE
[model] Import SDXL int8 in SHARK Turbine

### ISSUE THREAD

**Issue by antiagainst** [nod-ai/SHARK-Turbine#670]
- [x] Ensure we int8 matmul
- [ ] Ensure we have conv
- [x] Ensure both exsi A and B for matmul/conv

**Comment by stellaraccident** [comment]
I think we can call this done as this seemed focused on initial model import and test, which has now been done. Created https://github.com/nod-ai/sharktank/issues/73 to track it going into the overall pipeline.
