### ISSUE TITLE
Onnx.Col2Im

### ISSUE THREAD

**Issue by vivekkhandelwal1** [nod-ai/SHARK-Turbine#680]

**Comment by vivekkhandelwal1** [comment]
Assigned to @vinayakdsci

**Comment by vivekkhandelwal1** [comment]
Hi @vinayaksci, how're we doing on this op lowering?

**Comment by vinayakdsci** [comment]
@vivekkhandelwal1 Hi! I have had some progress implementing the op. I expect it will be finished in a day or two.

**Comment by vivekkhandelwal1** [comment]
Closed by https://github.com/llvm/torch-mlir/pull/3424
