### ISSUE TITLE
[matmul] Investgate better software pipelining

### ISSUE THREAD

**Issue by antiagainst** [nod-ai/SHARK-Turbine#686]
Right now we have a pretty straightforward shared memory [prefetch pipeline](https://github.com/iree-org/iree/pull/16723). We need to investigate if there are more advanced software pipelining techniques that can help to improve matmul performance.

**Comment by kuhar** [comment]
Related: https://github.com/nod-ai/playbook/issues/58

**Comment by kuhar** [comment]
Closing to dedupe with https://github.com/nod-ai/playbook/issues/58
