### ISSUE TITLE
Scatter

### ISSUE THREAD

**Issue by suryajasper** [nod-ai/SHARK-Turbine#708]
ONNX to torch to linalg lowering for Onnx.Scatter operation
Assigned to @suryajasper

**Comment by suryajasper** [comment]
Opened pull request: https://github.com/llvm/torch-mlir/pull/3395

**Comment by vivekkhandelwal1** [comment]
> Opened pull request: [llvm/torch-mlir#3395](https://github.com/llvm/torch-mlir/pull/3395)

@suryajasper, you mentioned the wrong PR. Correct one is https://github.com/llvm/torch-mlir/pull/3400
