### ISSUE TITLE
GRU

### ISSUE THREAD

**Issue by renxida** [nod-ai/SHARK-Turbine#723]
taking these because these are going to be similar to https://github.com/nod-ai/SHARK-Turbine/issues/315 (lstm)

**Comment by renxida** [comment]
rnn and gru should be doable with a refactoring & adding some helper functions in:

https://github.com/nod-ai/SHARK-Turbine/issues/315

**Comment by vivekkhandelwal1** [comment]
@renxida, can you please create 2 separate issues? That way, it would be easy to track them.

**Comment by renxida** [comment]
@vivekkhandelwal1 gru and lstm are special cases of rnn, and i expect that if i modify my lstm code to support RNNs in general, the same pr would support GRU also

**Comment by vivekkhandelwal1** [comment]
> @vivekkhandelwal1 gru and lstm are special cases of rnn, and i expect that if i modify my lstm code to support RNNs in general, the same pr would support GRU also

That's fine. I'll create a PR that will add 4 ops but in order to track them I have created 4 different issues. I'm just saying it's easy to track each op with a different issue instead of having multiple ops in the same issue.

**Comment by renxida** [comment]
oh ok! gotcha. i was assuming that there should be a 1-1 correspondance between issues and PRs. Will create another issue.
