### ISSUE TITLE
MelWeightMatrix

### ISSUE THREAD

**Issue by vivekkhandelwal1** [nod-ai/SHARK-Turbine#738]

**Comment by PhaneeshB** [comment]
[Onnx Docu](https://onnx.ai/onnx/operators/onnx__MelWeightMatrix.html)

For folks (like me) who are new to Mel Spectrogram in audio signal processing [here's a link](https://medium.com/analytics-vidhya/understanding-the-mel-spectrogram-fca2afa2ce53) that helped me get some context.

On searching for associated torchaudio Ops, I found that there is a [`MelScale`](https://pytorch.org/audio/main/generated/torchaudio.transforms.MelScale.html#melscale) Op in torchaudio.transforms that converts an STFT to a mel scaled STFT ( which is sort of what the MelWeightMatrix is supposed to do after we create it).
Looking at the [source ](https://pytorch.org/audio/main/_modules/torchaudio/transforms/_transforms.html#MelScale)for MelScale, it's a matmul (+ some transposes to align everything) between the input STFT with the [melscale_fbanks](https://pytorch.org/audio/main/generated/torchaudio.functional.melscale_fbanks.html#torchaudio-functional-melscale-fbanks) matrix which is what we expect from `onnx.MelWeightMatrix` 

So there is almost a 1:1 mapping from [onnx.MelWeightMatrix](https://onnx.ai/onnx/operators/onnx__MelWeightMatrix.html) to [melscale_fbanks](https://pytorch.org/audio/main/generated/torchaudio.functional.melscale_fbanks.html#torchaudio-functional-melscale-fbanks)

|onnx|torch|Comment|
|---|---|---|
| num_mel_bins | n_mels ||
| dft_length | n_freqs | n_freqs will need to passed as floor(dft_length/2)+1 as that is the expected output size |
| sample_rate | sample_rate ||
| lower_edge_hertz | f_min | both in Hz|
| upper_edge_hertz | f_max| both in Hz|
|-| norm | use torch default|
|-|mel_scale|use torch default|
|attr: output_type|-| depends on input so if attr is set in onnx would need to be handled explicitly |



One thing to note when actually using in a model is
that onnx.MelWeightMatrix requires :
> In the returned matrix, all the triangles (filterbanks) have a peak value of 1.0.

Whereas melscale_fbanks notes that :
> For the sake of the numerical compatibility with librosa, not all the coefficients in the resulting filter bank has magnitude of 1.

**Comment by PhaneeshB** [comment]
https://github.com/llvm/torch-mlir/pull/3503
