### ISSUE TITLE
[tuning] Tune int8 model dispatches

### ISSUE THREAD

**Issue by MaheshRavishankar** [nod-ai/SHARK-Turbine#751]

**Comment by antiagainst** [comment]
Update 7/8: need to extend to support int8/int32 and batch mmt.

**Comment by kuhar** [comment]
cc: @RattataKing

**Comment by kuhar** [comment]
Top matmuls:
![image](https://github.com/user-attachments/assets/751041c5-b833-4f64-9f5c-4d7b7badae7a)

Tuning progress:
1. [ ] `matmul_like_2x1024x10240x1280_i8xi8xi32` --> small improvement (0.1 ms), need to revisit
2. [x] `matmul_like_2x1024x1280x5120_i8xi8xi32` --> 0.8 ms down: https://github.com/nod-ai/sdxl-scripts/commit/f4aa06df048e272d84301d212523a0af065b04da

**Comment by kuhar** [comment]
# Conv Tuning Progress

![image](https://github.com/user-attachments/assets/81d68217-4209-4f29-9cc5-968bce15764d)

## Conv 2D

No | Done? | shape | ms | Improvement [ms] | Commit
-- | -- | -- | -- | -- | --
1 |   | conv_2d_nhwc_hwcf_2x32x32x1280x3x3x1280_i8xi8xi32 | 1.023439 |   |  
2 |   | conv_2d_nhwc_hwcf_2x32x32x1280x3x3x2560_i8xi8xi32 | 0.982422 |   |  
3 |   | conv_2d_nhwc_hwcf_2x64x64x1280x3x3x1280_i8xi8xi32 | 0.923829 |   |  
4 |   | conv_2d_nhwc_hwcf_2x64x64x640x3x3x640_i8xi8xi32 | 0.781249 |   |  
5 | Dupe | conv_2d_nhwc_hwcf_2x32x32x1280x3x3x1280_i8xi8xi32 | 0.771484 |   |  
6 |   | conv_2d_nhwc_hwcf_2x128x128x320x3x3x640_i8xi8xi32 | 0.740235 |   |  
7 |   | conv_2d_nhwc_hwcf_2x32x32x640x3x3x640_i8xi8xi32 | 0.699219 |   |  
8 |   | conv_2d_nhwc_hwcf_2x128x128x640x3x3x640_i8xi8xi32 | 0.6875 |   |  
9 |   | conv_2d_nhwc_hwcf_2x128x128x320x3x3x960_i8xi8xi32 | 0.570312 |   |  
10 |   | conv_2d_nhwc_hwcf_2x128x128x320x3x3x320_i8xi8xi32 | 0.5625 |   |  
11 |   | conv_2d_nhwc_hwcf_2x64x64x640x3x3x1920_i8xi8xi32 | 0.515625 |   |  
12 | Dupe | ~~conv_2d_nhwc_hwcf_2x32x32x1280x3x3x1280_i8xi8xi32~~ | 0.501953 |   |  
13 |   | conv_2d_nhwc_hwcf_2x64x64x320x3x3x320_i8xi8xi32 | 0.382812 |   |  
14 |   | conv_2d_nhwc_hwcf_2x32x32x1280x3x3x1920_i8xi8xi32 | 0.378906 |   |  
15 | Dupe  | ~~conv_2d_nhwc_hwcf_2x128x128x320x3x3x320_i8xi8xi32~~ | 0.375 |   |  
16 |   | conv_2d_nhwc_hwcf_2x64x64x640x3x3x1280_i8xi8xi32 | 0.335937 |   |  
17 | Dupe | ~~conv_2d_nhwc_hwcf_2x32x32x1280x3x3x1280_i8xi8xi32~~ | 0.259766 |   |  
18 |   | conv_2d_nhwc_hwcf_2x64x64x640x3x3x960_i8xi8xi32 | 0.25 |   |

**Comment by kuhar** [comment]
Newest trace

## Overall
![image](https://github.com/user-attachments/assets/1cab91a9-1659-4c07-9e4d-0292548e2f23)

## Matmuls
![image](https://github.com/user-attachments/assets/804705a7-06e9-4fab-8aab-59e5b196f5ed)

## Convs
![image](https://github.com/user-attachments/assets/65cbe8d9-841b-4d1d-899e-2a1b1af53a30)

**Comment by kuhar** [comment]
Newest trace as of https://github.com/nod-ai/sdxl-scripts/commit/0eb7ef0880285958ba8b29f8f886449932ec2190 (no horizontal fusion)

## Overall
![image](https://github.com/user-attachments/assets/af38d2a0-6bf8-4eaf-9e14-926cfc88f810)

## Matmuls
![image](https://github.com/user-attachments/assets/6034c39a-e245-4a64-beb8-191a0b48a329)

## Convs
![image](https://github.com/user-attachments/assets/7715df92-0fc5-4dae-9e39-d201dc525650)

**Comment by kuhar** [comment]
## Contractions

No | Done? | shape | ms | Improvement [ms] | Commit
-- | -- | -- | -- | -- | --
1 |   | matmul_like_2x20x1024x64x1280_i8xi8xi32 | 6.551762 |   |  
5 |   | matmul_like_2x20x64x64x2048_i8xi8xi32 | 2.011717 |   |  
7 |   | matmul_like_2x10x4096x64x640_i8xi8xi32 | 0.870121 |   |  
9 |   | matmul_like_2x10x64x64x2048_i8xi8xi32 | 0.344728 |   |

**Comment by kuhar** [comment]
I just double checked the total gain from tuning and it should be around 3.8 ms ==> 7.5%
