### ISSUE TITLE
onnx.Flatten

### ISSUE THREAD

**Issue by AmosLewis** [nod-ai/SHARK-Turbine#780]
previous pr: https://github.com/llvm/torch-mlir/pull/2760

New error for XSJ vision models. This op failed on most of the f32 vision models in XSJ.
```
DarkNet53.default.onnx.torch.mlir:238:12: error: failed to legalize operation 'torch.operator' that was explicitly marked illegal
    %234 = torch.operator "onnx.Flatten"(%233) {torch.onnx.axis = 1 : si64} : (!torch.vtensor<[1,1024,1,1],f32>) -> !torch.vtensor<[1,1024],f32> 
           ^
DarkNet53.default.onnx.torch.mlir:238:12: note: see current operation: %1229 = "torch.operator"(%1228) <{name = "onnx.Flatten"}> {torch.onnx.axis = 1 : si64} : (!torch.vtensor<[1,1024,1,1],f32>) -> !torch.vtensor<[1,1024],f32>
```

**Comment by vivekkhandelwal1** [comment]
Hi @AmosLewis, can you also add steps to reproduce this issue?

**Comment by vivekkhandelwal1** [comment]
> previous pr: [llvm/torch-mlir#2760](https://github.com/llvm/torch-mlir/pull/2760)
> 
> New error for XSJ vision models. This op failed on most of the f32 vision models in XSJ.
> 
> ```
> DarkNet53.default.onnx.torch.mlir:238:12: error: failed to legalize operation 'torch.operator' that was explicitly marked illegal
>     %234 = torch.operator "onnx.Flatten"(%233) {torch.onnx.axis = 1 : si64} : (!torch.vtensor<[1,1024,1,1],f32>) -> !torch.vtensor<[1,1024],f32> 
>            ^
> DarkNet53.default.onnx.torch.mlir:238:12: note: see current operation: %1229 = "torch.operator"(%1228) <{name = "onnx.Flatten"}> {torch.onnx.axis = 1 : si64} : (!torch.vtensor<[1,1024,1,1],f32>) -> !torch.vtensor<[1,1024],f32>
> ```

I'm able to lower the below IR:
```
func.func @test_flatten_4d_axis_2(%arg0: !torch.vtensor<[1,1024,1,1],f32>) -> !torch.vtensor<[1,1024],f32> attributes {torch.onnx_meta.ir_version = 7 : si64, torch.onnx_meta.opset_version = 13 : si64, torch.onnx_meta.producer_name = "backend-test", torch.onnx_meta.producer_version = ""} {
  %234 = torch.operator "onnx.Flatten"(%arg0) {torch.onnx.axis = 1 : si64} : (!torch.vtensor<[1,1024,1,1],f32>) -> !torch.vtensor<[1,1024],f32> 
  return %234 : !torch.vtensor<[1,1024],f32>
}
```

got the following resultant IR:
```
module {
  ml_program.global private mutable @global_seed(dense<0> : tensor<i64>) : tensor<i64>
  func.func @test_flatten_4d_axis_2(%arg0: tensor<1x1024x1x1xf32>) -> tensor<1x1024xf32> {
    %collapsed = tensor.collapse_shape %arg0 [[0], [1, 2, 3]] : tensor<1x1024x1x1xf32> into tensor<1x1024xf32>
    return %collapsed : tensor<1x1024xf32>
  }
}
```

**Comment by vivekkhandelwal1** [comment]
Fixed by https://github.com/llvm/torch-mlir/pull/3560
