### ISSUE TITLE
Find a more robust and versioned approach to compile flag setting.

### ISSUE THREAD

**Issue by monorimet** [nod-ai/SHARK-Turbine#787]
Right now, we handle compile flags in [sd_inference/utils.py](https://github.com/nod-ai/SHARK-Turbine/blob/main/models/turbine_models/custom_models/sd_inference/utils.py) and pass in some combination of MLIR, keywords, device, IREE target, model name, etc. to compile a list of IREE compile flags to use.

This would be better managed by a repository of flag files, parametrized by pinned IREE "flag versions" (we move the SHA every time we need to update flags for a IREE-side change and just hardcode that SHA in utils.py, maybe) then by model, then by configuration (think the same configs we make unique .vmfb filenames for)

More on this later, but putting a bookmark here so it doesn't get lost.

**Comment by vivekkhandelwal1** [comment]
Closed through https://github.com/nod-ai/SHARK-Turbine/pull/786
