### ISSUE TITLE
failed to legalize operation onnx.If

### ISSUE THREAD

**Issue by pdhirajkumarprasad** [nod-ai/SHARK-Turbine#815]
In e2e shark test suite, we are seeing error as failed to legalize operation onnx.If. Detail will be added

**Comment by kumardeepakamd** [comment]
@renxida seems to have worked on it https://github.com/llvm/torch-mlir/commit/33eef15e428f848e3848d1038ed71faab893a686

**Comment by kumardeepakamd** [comment]
https://github.com/nod-ai/SHARK-Turbine/issues/696 is already open
