### ISSUE TITLE
Failed to legalize operation `onnx.Loop`.

### ISSUE THREAD

**Issue by vinayakdsci** [nod-ai/SHARK-Turbine#818]
The ONNX operation `onnx.Loop` fails with `failed to legalize operation 'onnx.Loop'` during lowering, as reported in https://github.com/nod-ai/SHARK-Turbine/issues/812.

More details will be added later.

**Comment by kumardeepakamd** [comment]
https://github.com/nod-ai/SHARK-Turbine/issues/332 already tracks this
