### ISSUE TITLE
Add developer setup documentation to README

### ISSUE THREAD

**Issue by stellaraccident** [nod-ai/SHARK-Turbine#9]
The CMake command is correct. A couple of things are missing:

```
# For editable shark-turbine package
pip install -e .
# For compiler/runtime deps
source .env && export PYTHONPATH
```

Then should be able to:

```
pytest
```

**Comment by 123epsilon** [comment]
A note for later: Mac OS doesn't seem to support LLD, so in order to build for development I had to disable LLD in the cmake options: `-DIREE_ENABLE_LLD=OFF`

**Comment by vivekkhandelwal1** [comment]
Hi @stellaraccident, I'm working on clearing up the stale issues in Turbine and Torch-MLIR. Just wanted to confirm, if this issue is still relevant or not.
