### ISSUE TITLE
Lowering PyTorch Models to MLIR Linalg Dialect in Shark-Turbine

### ISSUE THREAD

**Issue by alecerio** [nod-ai/SHARK-Turbine#99]
#### Description

I am currently using Shark-Turbine for lowering my PyTorch neural network models to MLIR code. However, I've noticed that the output is in the Torch dialect and I need it to be in the MLIR Linalg dialect. 

#### Questions

1. Is there an option in the Shark-Turbine API to lower PyTorch models directly to the MLIR Linalg dialect?
2. I would appreciate any suggestions or guidance on how to achieve the desired lowering from PyTorch to MLIR in the Linalg dialect or from Torch dialect to Linalg dialect, whether through Shark-Turbine or any other methods or tools that you recommend.

Thank you in advance

**Comment by stellaraccident** [comment]
Generally, compilers like iree prefer to interchange at the torch dialect and then they have a conversion pipeline that imports it, incidentally taking it through linalg on the way. But we also have compiler specific lowerings and opinions in the import pipeline

**Comment by alecerio** [comment]
Thanks for the prompt reply,
Does it mean that there is already a way, even if partially implemented, to get mlir code with linalg dialect?

**Comment by dan-garvey** [comment]
yes absolutely. If you're using the aot.export api like in the simple mlp example:

```
class MLP(nn.Module):
    def __init__(self):
        super().__init__()
        self.layer0 = nn.Linear(8, 8, bias=True)
        self.layer1 = nn.Linear(8, 4, bias=True)
        self.layer2 = nn.Linear(4, 2, bias=True)
        self.layer3 = nn.Linear(2, 2, bias=True)

    def forward(self, x: torch.Tensor):
        x = self.layer0(x)
        x = torch.sigmoid(x)
        x = self.layer1(x)
        x = torch.sigmoid(x)
        x = self.layer2(x)
        x = torch.sigmoid(x)
        x = self.layer3(x)
        return x


model = MLP()
example_x = torch.empty(97, 8, dtype=torch.float32)
exported = aot.export(model, example_x)
aot.CompiledModule.run_import(exported.compiled_module)
exported.print_readable()
compiled_binary = exported.compile(save_to=None)
```

if you change the last few lines to:

```
model = MLP()
example_x = torch.empty(97, 8, dtype=torch.float32)
exported = aot.export(model, example_x)
aot.CompiledModule.run_import(exported.compiled_module) #This is the line that brings it to linalg
exported.print_readable()
compiled_binary = exported.compile(save_to=None)
```

this should print the linalg ir for you. If you want to save to a file you can do:

`exported.save_mlir("my_linalg_output.mlir")` to save your linalg output. (If you end in .mlirbc you'll get bytecode instead)

**Comment by alecerio** [comment]
Thank you so much and sorry for the late reply.
I try to use the code provided.

**Comment by alecerio** [comment]
It works, thank you.
